# Generated by Django 2.1.2 on 2019-02-06 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190206_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpasswordlinks',
            name='ip_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
