# Generated by Django 2.1.2 on 2019-04-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190408_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivationlink',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
