# Generated by Django 2.2.8 on 2020-04-05 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_auto_20200108_1533"),
    ]

    operations = [
        migrations.CreateModel(
            name="RlcSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_record_pool", models.BooleanField(default=False)),
                (
                    "rlc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rlc_settings",
                        to="api.Rlc",
                    ),
                ),
            ],
        ),
    ]
