# Generated by Django 2.2.8 on 2020-04-13 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_auto_20200228_0139"),
        ("api", "0013_rlcsettings"),
    ]

    operations = []
