# Generated by Django 3.0 on 2020-11-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_useractivitypath_usersession_usersessionpath"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivitypath",
            name="path",
            field=models.CharField(max_length=1024),
        ),
    ]
