# Generated by Django 3.0 on 2021-03-12 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20210309_1138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
