# Generated by Django 3.0 on 2021-03-18 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20210317_1048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AlterUniqueTogether(
            name='usersrlckeys',
            unique_together={('user', 'rlc')},
        ),
    ]
