# Generated by Django 3.0 on 2021-03-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_delete_language'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersrlckeys',
            unique_together={('user', 'rlc')},
        ),
    ]
