# Generated by Django 3.1.7 on 2021-03-24 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20210324_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuserrequest',
            name='request_from',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accepted2', to=settings.AUTH_USER_MODEL),
        ),
    ]
