# Generated by Django 3.1.7 on 2021-03-30 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_merge_20210330_1504"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "UserProfile",
                "verbose_name_plural": "UserProfiles",
            },
        ),
        migrations.AlterField(
            model_name="group",
            name="group_members",
            field=models.ManyToManyField(
                blank=True, related_name="group_members", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
