# Generated by Django 3.1.6 on 2021-04-29 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20210423_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_members',
            field=models.ManyToManyField(blank=True, related_name='rlcgroups', to=settings.AUTH_USER_MODEL),
        ),
    ]
