# Generated by Django 4.1.3 on 2022-12-08 18:04

from django.db import migrations


def create_fixtures(apps, schema_editor):
    from core.fixtures import (
        create_collab_permissions,
        create_folder_permissions,
        create_permissions,
    )

    Permission = apps.get_model("core", "Permission")
    create_permissions(Permission)

    CollabPermission = apps.get_model("core", "CollabPermission")
    create_collab_permissions(CollabPermission)

    FolderPermission = apps.get_model("core", "FolderPermission")
    create_folder_permissions(FolderPermission)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_fixtures, reverse_code=migrations.RunPython.noop)
    ]
