# Generated by Django 4.1.3 on 2022-12-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_fixtures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rlcuser",
            name="key",
            field=models.JSONField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
