# Generated by Django 4.1.3 on 2022-12-08 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_rlcuser_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="rlc_old",
        ),
    ]
