# Generated by Django 4.1.3 on 2022-12-08 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_userprofile_rlc_old"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="olduserencryptionkeys",
            name="user",
        ),
        migrations.DeleteModel(
            name="OldRlcEncryptionKeys",
        ),
        migrations.DeleteModel(
            name="OldUserEncryptionKeys",
        ),
    ]
