# Generated by Django 4.1.3 on 2022-12-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_olduserencryptionkeys_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="maildomain",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
