# Generated by Django 4.1.3 on 2022-12-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_maildomain_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(to="core.rlcuser"),
        ),
    ]
