# Generated by Django 4.1.3 on 2022-12-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_event_attendees"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="attendees",
        ),
    ]
