# Generated by Django 4.1.3 on 2022-12-21 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_event_attendees"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attendance",
                    models.CharField(
                        choices=[("Y", "Attending"), ("U", "Unsure"), ("N", "Absent")],
                        default="U",
                        max_length=1,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendances",
                        to="core.event",
                    ),
                ),
                (
                    "rlc_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="core.rlcuser",
                    ),
                ),
            ],
        ),
    ]
