# Generated by Django 4.1.4 on 2022-12-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_foldersfolder_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="encryptedrecorddocument",
            name="folder_uuid",
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.RenameField(
            model_name="encryptedrecorddocument",
            old_name="created_on",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="encryptedrecorddocument",
            old_name="last_edited",
            new_name="updated",
        ),
        migrations.AlterField(
            model_name="encryptedrecorddocument",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
