# Generated by Django 4.1.3 on 2022-12-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_attendance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="attendance",
            new_name="status",
        ),
    ]
