# Generated by Django 4.1.4 on 2022-12-22 10:34

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_encryptedrecorddocument_org"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryptedrecorddocument",
            name="key",
            field=models.SlugField(
                allow_unicode=True, default=None, max_length=1000, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="encryptedrecorddocument",
            name="org",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="core.org",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="encryptedrecorddocument",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
