# Generated by Django 4.1.4 on 2022-12-22 11:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_encryptedrecorddocument_key_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="encryptedrecorddocument",
            old_name="key",
            new_name="location",
        ),
    ]
