# Generated by Django 4.1.4 on 2022-12-30 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_encryptedrecordmessage_folder_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="encryptedrecordmessage",
            name="org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="core.org",
            ),
        ),
    ]
