# Generated by Django 4.1.4 on 2022-12-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_encryptedrecordmessage_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="encryptedrecordmessage",
            name="enc_message",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="encryptedrecordmessage",
            name="key",
            field=models.JSONField(null=True),
        ),
    ]
