# Generated by Django 4.1.4 on 2022-12-30 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_encryptedrecordmessage_enc_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryptedrecordmessage",
            name="record",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="core.record",
            ),
        ),
    ]
