# Generated by Django 4.1.4 on 2023-01-01 15:23

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_encryptedrecordmessage_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="folder_uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="key",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="name",
            field=models.CharField(default="-", max_length=200),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
