# Generated by Django 2.2.8 on 2020-08-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_auto_20200811_0938"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("RECORD__CREATED", "RECORD__CREATED"),
                    ("RECORD__UPDATED", "RECORD__UPDATED"),
                    ("RECORD__DELETED", "RECORD__DELETED"),
                    ("RECORD__RECORD_MESSAGE_ADDED", "RECORD__RECORD_MESSAGE_ADDED"),
                    ("RECORD__RECORD_DOCUMENT_ADDED", "RECORD__RECORD_DOCUMENT_ADDED"),
                    (
                        "RECORD__RECORD_DOCUMENT_MODIFIED",
                        "RECORD__RECORD_DOCUMENT_MODIFIED",
                    ),
                    ("RECORD__CLIENT_MODIFIED", "RECORD__CLIENT_MODIFIED"),
                    ("GROUP__ADDED_ME", "GROUP__ADDED_ME"),
                    ("GROUP__REMOVED_ME", "GROUP__REMOVED_ME"),
                ],
                default="",
                max_length=75,
            ),
        ),
    ]
