# Generated by Django 2.2.8 on 2020-08-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_auto_20200812_0911"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="description_text",
            new_name="text",
        ),
    ]
