# Generated by Django 4.1.4 on 2023-01-04 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_alter_questionnaire_uuid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailaddress",
            options={
                "ordering": ["localpart"],
                "verbose_name": "MailAddress",
                "verbose_name_plural": "MailAddress",
            },
        ),
        migrations.AddField(
            model_name="recordaccess",
            name="processor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_record_accesses",
                to="core.rlcuser",
            ),
        ),
        migrations.AddField(
            model_name="recordaccess",
            name="requestor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_record_accesses",
                to="core.rlcuser",
            ),
        ),
        migrations.AddField(
            model_name="recorddeletion",
            name="processor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_record_deletions",
                to="core.rlcuser",
            ),
        ),
        migrations.AddField(
            model_name="recorddeletion",
            name="requestor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_record_deletions",
                to="core.rlcuser",
            ),
        ),
    ]
