# Generated by Django 4.1.4 on 2023-01-05 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_alter_recordaccess_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recordaccess",
            name="processed_by",
        ),
        migrations.RemoveField(
            model_name="recordaccess",
            name="requested_by",
        ),
        migrations.RemoveField(
            model_name="recorddeletion",
            name="processed_by",
        ),
        migrations.RemoveField(
            model_name="recorddeletion",
            name="requested_by",
        ),
        migrations.AlterField(
            model_name="recordaccess",
            name="requestor",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requested_record_accesses",
                to="core.rlcuser",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recorddeletion",
            name="requestor",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requested_record_deletions",
                to="core.rlcuser",
            ),
            preserve_default=False,
        ),
    ]
