# Generated by Django 4.1.5 on 2023-01-16 12:35

import uuid

import django.db.models.deletion
from django.db import migrations, models

import core.seedwork.aggregate
import core.upload.models.upload


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_remove_recordaccess_processed_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("folder_uuid", models.UUIDField()),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("key", models.JSONField()),
                ("disabled", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.org"
                    ),
                ),
            ],
            options={
                "verbose_name": "UploadLink",
                "verbose_name_plural": "UploadLinks",
            },
            bases=(core.seedwork.aggregate.Aggregate, models.Model),
        ),
        migrations.CreateModel(
            name="UploadFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                (
                    "file",
                    models.FileField(upload_to=core.upload.models.upload.file_path),
                ),
                ("key", models.JSONField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="core.uploadlink",
                    ),
                ),
            ],
            options={
                "verbose_name": "UploadFile",
                "verbose_name_plural": "UploadFiles",
            },
        ),
    ]
