# Generated by Django 4.1.5 on 2023-01-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_uploadlink_uploadfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recorddeletion",
            name="explanation",
            field=models.TextField(blank=True),
        ),
    ]
