# Generated by Django 4.1.5 on 2023-01-31 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_alter_recorddeletion_explanation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="legalrequirementuser",
            options={
                "ordering": ["legal_requirement__order"],
                "verbose_name": "LegalRequirementUser",
                "verbose_name_plural": "LegalRequirementUsers",
            },
        ),
    ]
