# Generated by Django 4.1.7 on 2023-03-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_multifactorauthenticationsecret"),
    ]

    operations = [
        migrations.AddField(
            model_name="multifactorauthenticationsecret",
            name="enabled",
            field=models.BooleanField(default=False),
        ),
    ]
