# Generated by Django 3.1.7 on 2021-03-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_auto_20210318_1915"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
