# Generated by Django 4.1.7 on 2023-03-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_multifactorauthenticationsecret_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="foldersfolder",
            name="name_change_disabled",
            field=models.BooleanField(default=False),
        ),
    ]
