# Generated by Django 4.1.7 on 2023-03-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_recordsrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordsrecord",
            name="folder_uuid",
            field=models.UUIDField(db_index=True, default=None),
            preserve_default=False,
        ),
    ]
