# Generated by Django 4.1.7 on 2023-03-27 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_recordsview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordsrecord",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records_records",
                to="core.org",
            ),
        ),
        migrations.CreateModel(
            name="RecordsDeletion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(db_index=True, unique=True)),
                ("explanation", models.TextField(blank=True)),
                ("processed", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("re", "Requested"),
                            ("gr", "Granted"),
                            ("de", "Declined"),
                        ],
                        default="re",
                        max_length=2,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "processor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records_processed_deletions",
                        to="core.rlcuser",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deletions",
                        to="core.recordsrecord",
                    ),
                ),
                (
                    "requestor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records_requested_deletions",
                        to="core.rlcuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordsDeletion",
                "verbose_name_plural": "RecordsDeletions",
                "ordering": ["-created"],
            },
        ),
    ]
