# Generated by Django 4.1.7 on 2023-03-27 11:47

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_alter_recordsrecord_org_recordsdeletion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordsdeletion",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
