# Generated by Django 4.1.7 on 2023-03-27 13:35

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_alter_recordsdeletion_uuid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recordsdeletion",
            options={
                "ordering": ["-created"],
                "verbose_name": "Records-Deletion",
                "verbose_name_plural": "Records-Deletions",
            },
        ),
        migrations.AlterModelOptions(
            name="recordsrecord",
            options={
                "verbose_name": "Records-Record",
                "verbose_name_plural": "Records-Records",
            },
        ),
        migrations.AlterModelOptions(
            name="recordsview",
            options={
                "verbose_name": "Records-View",
                "verbose_name_plural": "Records-Views",
            },
        ),
        migrations.CreateModel(
            name="RecordsAccessRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("processed_on", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("re", "requested"),
                            ("gr", "granted"),
                            ("de", "declined"),
                        ],
                        default="re",
                        max_length=2,
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "processor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records_processed_access_requests",
                        to="core.rlcuser",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_requests",
                        to="core.recordsrecord",
                    ),
                ),
                (
                    "requestor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records_requested_access_requests",
                        to="core.rlcuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordsAccessRequest",
                "verbose_name_plural": "RecordsAccessRequestes",
                "ordering": ["-created"],
            },
        ),
    ]
