# Generated by Django 3.1.7 on 2021-03-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_auto_20210323_2026"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="city",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="postal_code",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="street",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
