# Generated by Django 4.1.7 on 2023-03-27 16:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_recordsview_ordering"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recordsview",
            options={
                "ordering": ["org", "ordering"],
                "verbose_name": "Records-View",
                "verbose_name_plural": "Records-Views",
            },
        ),
    ]
