# Generated by Django 4.1.7 on 2023-04-06 21:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_alter_recordencryptedfilefield_uuid_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Event",
            new_name="EventsEvent",
        ),
    ]
