# Generated by Django 3.1.7 on 2021-03-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_auto_20210326_1459"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="locked",
            field=models.BooleanField(default=False),
        ),
    ]
