# Generated by Django 4.1.7 on 2023-05-29 20:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_eventsevent_level"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="_members",
            new_name="members",
        ),
    ]
