# Generated by Django 4.1.7 on 2023-06-17 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0051_rename__members_group_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="legalrequirementevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legal_requirement_events",
                to="core.rlcuser",
            ),
        ),
    ]
