# Generated by Django 3.1.7 on 2021-03-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_auto_20210326_1602"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "ordering": ["name"],
                "verbose_name": "UserProfile",
                "verbose_name_plural": "UserProfiles",
            },
        ),
    ]
