# Generated by Django 4.1.7 on 2023-06-17 10:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_legalrequirementevent_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="legalrequirementevent",
            old_name="actor",
            new_name="actor_old",
        ),
    ]
