# Generated by Django 4.1.7 on 2023-06-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0053_rename_actor_legalrequirementevent_actor_old"),
    ]

    operations = [
        migrations.AddField(
            model_name="legalrequirementevent",
            name="actor",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
