# Generated by Django 4.1.7 on 2023-06-17 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0054_legalrequirementevent_actor"),
    ]

    operations = [
        migrations.AddField(
            model_name="legalrequirementevent",
            name="legal_requirement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.legalrequirement",
            ),
        ),
    ]
