# Generated by Django 4.2.2 on 2023-06-17 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0056_alter_legalrequirementevent_legal_requirement_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legalrequirementevent",
            name="legal_requirement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="core.legalrequirement",
            ),
        ),
    ]
