# Generated by Django 4.2.2 on 2023-06-19 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_alter_legalrequirementevent_legal_requirement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="legalrequirement",
            name="rlc_users",
        ),
        migrations.RemoveField(
            model_name="legalrequirementevent",
            name="actor_old",
        ),
        migrations.RemoveField(
            model_name="legalrequirementevent",
            name="legal_requirement_user",
        ),
        migrations.AlterField(
            model_name="legalrequirementevent",
            name="legal_requirement",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="core.legalrequirement",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="legalrequirementevent",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legal_requirement_events",
                to="core.rlcuser",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="LegalRequirementUser",
        ),
    ]
