# Generated by Django 3.1.6 on 2021-05-12 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_auto_20210429_1757"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user_record_state",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user_state",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="rlc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rlc_members",
                to="core.rlc",
            ),
        ),
        migrations.CreateModel(
            name="RlcUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "RlcUser",
                "verbose_name_plural": "RlcUsers",
            },
        ),
    ]
