# Generated by Django 4.2.5 on 2023-09-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0060_timelineevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="timelinefollowup",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
    ]
