# Generated by Django 4.2.5 on 2023-10-18 18:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0061_timelinefollowup_is_done"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recordtemplate",
            name="show",
        ),
    ]
