# Generated by Django 4.2.5 on 2023-10-18 18:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0062_remove_recordtemplate_show"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poolrecord",
            name="record",
        ),
        migrations.DeleteModel(
            name="PoolConsultant",
        ),
        migrations.DeleteModel(
            name="PoolRecord",
        ),
    ]
