# Generated by Django 4.2.5 on 2023-10-25 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0063_remove_poolrecord_record_delete_poolconsultant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recorddeletion",
            name="processor",
        ),
        migrations.RemoveField(
            model_name="recorddeletion",
            name="record",
        ),
        migrations.RemoveField(
            model_name="recorddeletion",
            name="requestor",
        ),
        migrations.DeleteModel(
            name="RecordAccess",
        ),
        migrations.DeleteModel(
            name="RecordDeletion",
        ),
    ]
