# Generated by Django 4.2.5 on 2023-10-25 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0064_remove_recorddeletion_processor_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Record",
            new_name="DataSheet",
        ),
    ]
