# Generated by Django 4.2.5 on 2023-10-25 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0065_rename_record_datasheet"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RecordTemplate",
            new_name="DataSheetTemplate",
        ),
    ]
