# Generated by Django 4.2.5 on 2023-10-25 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0066_rename_recordtemplate_datasheettemplate"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RecordStateField",
            new_name="DataSheetStateField",
        ),
        migrations.RenameModel(
            old_name="RecordUsersField",
            new_name="DataSheetUsersField",
        ),
    ]
