# Generated by Django 3.1.6 on 2021-06-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_rlcuser_accepted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rlc",
            name="note",
        ),
        migrations.RemoveField(
            model_name="rlc",
            name="part_of_umbrella",
        ),
        migrations.RemoveField(
            model_name="rlc",
            name="uni_tied",
        ),
    ]
