# Generated by Django 4.2.5 on 2023-10-25 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0067_rename_recordstatefield_datasheetstatefield_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RecordEncryptedFileField",
            new_name="DataSheetEncryptedFileField",
        ),
        migrations.RenameModel(
            old_name="RecordEncryptedSelectField",
            new_name="DataSheetEncryptedSelectField",
        ),
        migrations.RenameModel(
            old_name="RecordEncryptedStandardField",
            new_name="DataSheetEncryptedStandardField",
        ),
        migrations.RenameModel(
            old_name="RecordMultipleField",
            new_name="DataSheetMultipleField",
        ),
        migrations.RenameModel(
            old_name="RecordSelectField",
            new_name="DataSheetSelectField",
        ),
        migrations.RenameModel(
            old_name="RecordStandardField",
            new_name="DataSheetStandardField",
        ),
        migrations.RenameModel(
            old_name="RecordStatisticField",
            new_name="DataSheetStatisticField",
        ),
    ]
