# Generated by Django 4.2.5 on 2023-10-25 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0068_rename_recordencryptedfilefield_datasheetencryptedfilefield_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RecordEncryptedFileEntry",
            new_name="DataSheetEncryptedFileEntry",
        ),
        migrations.RenameModel(
            old_name="RecordEncryptedSelectEntry",
            new_name="DataSheetEncryptedSelectEntry",
        ),
        migrations.RenameModel(
            old_name="RecordEncryptedStandardEntry",
            new_name="DataSheetEncryptedStandardEntry",
        ),
        migrations.RenameModel(
            old_name="RecordMultipleEntry",
            new_name="DataSheetMultipleEntry",
        ),
        migrations.RenameModel(
            old_name="RecordSelectEntry",
            new_name="DataSheetSelectEntry",
        ),
        migrations.RenameModel(
            old_name="RecordStandardEntry",
            new_name="DataSheetStandardEntry",
        ),
        migrations.RenameModel(
            old_name="RecordStateEntry",
            new_name="DataSheetStateEntry",
        ),
        migrations.RenameModel(
            old_name="RecordStatisticEntry",
            new_name="DataSheetStatisticEntry",
        ),
        migrations.RenameModel(
            old_name="RecordUsersEntry",
            new_name="DataSheetUsersEntry",
        ),
    ]
