# Generated by Django 4.2.5 on 2023-10-25 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0069_rename_recordencryptedfileentry_datasheetencryptedfileentry_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RecordEncryptionNew",
            new_name="DataSheetEncryptionNew",
        ),
    ]
