# Generated by Django 3.1.6 on 2021-10-11 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_auto_20211011_2056"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loggedpath",
            options={
                "ordering": ["-time"],
                "verbose_name": "LoggedPath",
                "verbose_name_plural": "LoggedPaths",
            },
        ),
    ]
