# Generated by Django 4.2.5 on 2023-11-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0073_group_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="foldersfolder",
            name="enc_parent_key",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
