# Generated by Django 4.2.5 on 2023-11-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0074_foldersfolder_enc_parent_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="foldersfolder",
            name="group_keys",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
