# Generated by Django 4.2.5 on 2023-11-13 17:27

import uuid

import django.db.models.deletion
from django.db import migrations, models

import core.seedwork.aggregate


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0075_foldersfolder_group_keys"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collab",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("title", models.CharField(max_length=256)),
                ("folder_uuid", models.UUIDField()),
                ("history_enc", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collabs",
                        to="core.org",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collab",
                "verbose_name_plural": "Collabs",
            },
            bases=(core.seedwork.aggregate.Aggregate, models.Model),
        ),
    ]
