# Generated by Django 4.2.5 on 2023-11-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0076_collab"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="collab_migrated",
            field=models.BooleanField(default=False),
        ),
    ]
