# Generated by Django 4.2.5 on 2023-12-12 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0077_org_collab_migrated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="org",
            options={
                "ordering": ["name"],
                "verbose_name": "Org",
                "verbose_name_plural": "Orgs",
            },
        ),
        migrations.AlterModelOptions(
            name="rlcuser",
            options={
                "ordering": ["accepted", "locked", "is_active", "user__name"],
                "verbose_name": "OrgUser",
                "verbose_name_plural": "OrgUsers",
            },
        ),
    ]
