# Generated by Django 4.2.5 on 2023-12-12 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0078_alter_org_options_alter_rlcuser_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RlcUser",
            new_name="OrgUser",
        ),
        migrations.AlterModelTable(
            name="orguser",
            table="core_orguser",
        ),
    ]
