# Generated by Django 4.2.5 on 2023-12-12 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0079_rename_rlcuser_orguser_alter_orguser_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="orguser",
            table=None,
        ),
    ]
