# Generated by Django 4.2.5 on 2023-12-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0080_alter_orguser_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="new_records_have_inheritance_stop",
            field=models.BooleanField(default=True),
        ),
    ]
