# Generated by Django 4.2.5 on 2023-12-17 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0081_org_new_records_have_inheritance_stop"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "ordering": ["name"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
