# Generated by Django 4.2.5 on 2023-12-17 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0082_alter_userprofile_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questionnaire",
            options={
                "verbose_name": "QUE_Questionnaire",
                "verbose_name_plural": "QUE_Questionnaires",
            },
        ),
        migrations.AlterModelOptions(
            name="questionnaireanswer",
            options={
                "verbose_name": "QUE_QuestionnaireAnswer",
                "verbose_name_plural": "QUE_QuestionnaireAnswers",
            },
        ),
        migrations.AlterModelOptions(
            name="questionnairequestion",
            options={
                "ordering": ["order"],
                "verbose_name": "QUE_TemplateField",
                "verbose_name_plural": "QUE_TemplateFields",
            },
        ),
        migrations.AlterModelOptions(
            name="questionnairetemplate",
            options={
                "verbose_name": "QUE_Template",
                "verbose_name_plural": "QUE_Templates",
            },
        ),
        migrations.AlterModelOptions(
            name="questionnairetemplatefile",
            options={
                "verbose_name": "QUE_TemplateFile",
                "verbose_name_plural": "QUE_TemplateFiles",
            },
        ),
    ]
