# Generated by Django 4.2.5 on 2023-12-17 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0083_alter_questionnaire_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="internaluser",
            options={
                "verbose_name": "AUT_InternalUser",
                "verbose_name_plural": "AUT_InternalUsers",
            },
        ),
        migrations.AlterModelOptions(
            name="matrixuser",
            options={
                "ordering": ["user__name"],
                "verbose_name": "AUT_MatrixUser",
                "verbose_name_plural": "AUT_MatrixUsers",
            },
        ),
        migrations.AlterModelOptions(
            name="multifactorauthenticationsecret",
            options={
                "verbose_name": "AUT_MultiFactorAuthenticationSecret",
                "verbose_name_plural": "AUT_MultiFactorAuthenticationSecrets",
            },
        ),
        migrations.AlterModelOptions(
            name="orguser",
            options={
                "ordering": ["accepted", "locked", "is_active", "user__name"],
                "verbose_name": "AUT_OrgUser",
                "verbose_name_plural": "AUT_OrgUsers",
            },
        ),
        migrations.AlterModelOptions(
            name="statisticuser",
            options={
                "ordering": ["user__name"],
                "verbose_name": "AUT_StatisticUser",
                "verbose_name_plural": "AUT_StatisticUsers",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "ordering": ["name"],
                "verbose_name": "AUT_User",
                "verbose_name_plural": "AUT_Users",
            },
        ),
    ]
