# Generated by Django 4.2.5 on 2023-12-17 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0084_alter_internaluser_options_alter_matrixuser_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name": "ORG_Group", "verbose_name_plural": "ORG_Groups"},
        ),
        migrations.AlterModelOptions(
            name="meta",
            options={"verbose_name": "ORG_Meta", "verbose_name_plural": "ORG_Metas"},
        ),
        migrations.AlterModelOptions(
            name="note",
            options={
                "ordering": ["-created"],
                "verbose_name": "ORG_Note",
                "verbose_name_plural": "ORG_Notes",
            },
        ),
        migrations.AlterModelOptions(
            name="org",
            options={
                "ordering": ["name"],
                "verbose_name": "ORG_Org",
                "verbose_name_plural": "ORG_Orgs",
            },
        ),
        migrations.AlterModelOptions(
            name="orgencryption",
            options={
                "verbose_name": "ORG_UserRlcKeys",
                "verbose_name_plural": "ORG_UsersRlcKeys",
            },
        ),
    ]
