# Generated by Django 4.2.5 on 2023-12-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0086_remove_datasheet_old_client_delete_encryptedclient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionnaire",
            name="record",
        ),
        migrations.RemoveField(
            model_name="questionnairetemplate",
            name="records",
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="folder_uuid",
            field=models.UUIDField(),
        ),
    ]
