# Generated by Django 4.2.5 on 2023-12-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0087_remove_questionnaire_record_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="encryptedrecorddocument",
            name="record",
        ),
        migrations.AlterField(
            model_name="encryptedrecorddocument",
            name="folder_uuid",
            field=models.UUIDField(db_index=True),
        ),
    ]
