# Generated by Django 4.2.5 on 2023-12-26 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0088_remove_encryptedrecorddocument_record_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="legalrequirement",
            options={
                "ordering": ["order"],
                "verbose_name": "LEG_LegalRequirement",
                "verbose_name_plural": "LEG_LegalRequirements",
            },
        ),
        migrations.AlterModelOptions(
            name="legalrequirementevent",
            options={
                "verbose_name": "LEG_LegalRequirementEvent",
                "verbose_name_plural": "LEG_LegalRequirementEvents",
            },
        ),
    ]
