# Generated by Django 4.2.5 on 2024-02-19 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0089_alter_legalrequirement_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionnairetemplate",
            name="rlc",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questionnaire_templates",
                to="core.org",
            ),
        ),
    ]
