# Generated by Django 4.2.5 on 2024-02-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0090_alter_questionnairetemplate_rlc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryptedrecordmessage",
            name="folder_uuid",
            field=models.UUIDField(default=None),
            preserve_default=False,
        ),
    ]
