# Generated by Django 4.2.5 on 2024-02-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0093_add_mail_import"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailimport",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
    ]
