# Generated by Django 5.0.2 on 2024-03-12 10:58

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0094_mailimport_is_pinned"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailimport",
            options={
                "verbose_name": "MI_MailImport",
                "verbose_name_plural": "MI_MailImports",
            },
        ),
        migrations.AlterField(
            model_name="mailimport",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
