# Generated by Django 5.0.2 on 2024-03-13 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0096_alter_datasheet_folder_uuid"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DataSheetEncryptionNew",
        ),
    ]
