# Generated by Django 5.0.2 on 2024-03-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0097_delete_datasheetencryptionnew"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailimport",
            name="folder_uuid",
            field=models.UUIDField(db_index=True, default=None),
            preserve_default=False,
        ),
    ]
