# Generated by Django 5.0.2 on 2024-03-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0098_mailimport_folder_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailimport",
            name="cc",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
