# Generated by Django 5.0.2 on 2024-04-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0100_mailimport_org"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailimport",
            name="content",
        ),
        migrations.RemoveField(
            model_name="mailimport",
            name="subject",
        ),
        migrations.AddField(
            model_name="mailimport",
            name="enc_content",
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mailimport",
            name="enc_key",
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mailimport",
            name="enc_subject",
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
