# Generated by Django 5.0.2 on 2024-04-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0102_mailimport_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordsrecord",
            name="attributes",
            field=models.TextField(default="{}"),
        ),
    ]
