# Generated by Django 5.0.2 on 2024-04-28 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0103_recordsrecord_attributes"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FoldersFolder",
            new_name="FOL_Folder",
        ),
        migrations.AlterModelOptions(
            name="fol_folder",
            options={
                "ordering": ["name"],
                "verbose_name": "FOL_Folder",
                "verbose_name_plural": "FOL_Folders",
            },
        ),
    ]
