# Generated by Django 5.0.2 on 2024-05-17 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0105_fol_closuretable"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fol_closuretable",
            options={
                "ordering": ["parent", "child"],
                "verbose_name": "FOL_ClosureTable",
                "verbose_name_plural": "FOL_ClosureTable",
            },
        ),
    ]
