# Generated by Django 5.0.6 on 2024-05-17 07:18

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0106_alter_fol_closuretable_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Letterhead",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("address_line_1", models.CharField(max_length=256)),
                ("address_line_2", models.CharField(blank=True, max_length=256)),
                ("address_line_3", models.CharField(blank=True, max_length=256)),
                ("address_line_4", models.CharField(blank=True, max_length=256)),
                ("address_line_5", models.CharField(blank=True, max_length=256)),
                ("logo", models.ImageField(blank=True, upload_to="letterheads")),
                ("text_right", models.TextField(blank=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="letterheads",
                        to="core.org",
                    ),
                ),
            ],
            options={
                "verbose_name": "Letterhead",
                "verbose_name_plural": "Letterheads",
            },
        ),
    ]
