# Generated by Django 5.0.6 on 2024-05-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0107_letterhead"),
    ]

    operations = [
        migrations.AddField(
            model_name="letterhead",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="letterhead",
            name="name",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
