# Generated by Django 5.0.6 on 2024-05-21 09:12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0108_letterhead_description_letterhead_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("column_1", models.TextField(blank=True)),
                ("column_2", models.TextField(blank=True)),
                ("column_3", models.TextField(blank=True)),
                ("column_4", models.TextField(blank=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="footers",
                        to="core.org",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer",
                "verbose_name_plural": "Footers",
            },
        ),
    ]
