# Generated by Django 5.0.6 on 2024-05-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0109_footer"),
    ]

    operations = [
        migrations.AddField(
            model_name="footer",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="footer",
            name="name",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
