# Generated by Django 5.0.6 on 2024-07-02 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0110_footer_description_footer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="collab",
            name="footer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.footer",
            ),
        ),
        migrations.AddField(
            model_name="collab",
            name="letterhead",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.letterhead",
            ),
        ),
    ]
