# Generated by Django 3.2.15 on 2022-09-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0112_rename_rlc_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="rlcuser",
            name="frontend_settings",
            field=models.JSONField(null=True),
        ),
    ]
