# Generated by Django 5.0.6 on 2024-07-17 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0112_remove_collab_footer_remove_collab_letterhead_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="footer",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.footer",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="letterhead",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.letterhead",
            ),
        ),
        migrations.AddConstraint(
            model_name="template",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("letterhead__isnull", False),
                    ("footer__isnull", False),
                    _connector="OR",
                ),
                name="either_letterhead_or_footer",
            ),
        ),
    ]
