# Generated by Django 5.0.6 on 2024-07-17 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0113_alter_template_footer_alter_template_letterhead_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collab",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.template",
            ),
        ),
    ]
