# Generated by Django 5.0.6 on 2024-07-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0114_alter_collab_template"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="template",
            name="either_letterhead_or_footer",
        ),
    ]
