# Generated by Django 5.0.6 on 2024-07-21 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0115_remove_template_either_letterhead_or_footer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="letterhead",
            name="description",
        ),
        migrations.RemoveField(
            model_name="letterhead",
            name="name",
        ),
    ]
