# Generated by Django 4.0.7 on 2022-09-26 08:13

import django.db.models.deletion
from django.db import migrations, models


def move_org(apps, schema_editor):
    RlcUser = apps.get_model("core", "RlcUser")
    UserProfile = apps.get_model("core", "UserProfile")

    for u in UserProfile.objects.all():
        r = RlcUser.objects.filter(user=u).first()
        if r:
            r.org = u.rlc_old
            r.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0116_rename_rlc_userprofile_rlc_old"),
    ]

    operations = [
        migrations.AddField(
            model_name="rlcuser",
            name="org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="core.org",
            ),
        ),
        migrations.RunPython(move_org),
    ]
