# Generated by Django 5.0.6 on 2024-07-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0116_remove_letterhead_description_remove_letterhead_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footer",
            name="description",
        ),
        migrations.RemoveField(
            model_name="footer",
            name="name",
        ),
    ]
