# Generated by Django 5.0.6 on 2024-09-03 11:33

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0117_remove_footer_description_remove_footer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="uuid",
            field=models.UUIDField(unique=True),
        ),
        migrations.CreateModel(
            name="MailAttachement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_location",
                    models.SlugField(allow_unicode=True, max_length=1000, unique=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "mail_import",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachements",
                        to="core.mailimport",
                    ),
                ),
            ],
        ),
    ]
