# Generated by Django 5.0.8 on 2024-09-25 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0119_alter_mailattachement_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MailAttachement",
            new_name="MailAttachment",
        )
    ]
