# Generated by Django 5.0.8 on 2024-09-25 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0120_mailattachment_delete_mailattachement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailattachment",
            name="mail_import",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="core.mailimport",
            ),
        ),
    ]
