# Generated by Django 5.1.3 on 2024-12-03 15:00

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0123_add_todo"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="deadline",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
