# Generated by Django 4.0.7 on 2022-10-11 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.records.models.record
import core.seedwork.encryption


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0123_remove_group_group_members"),
    ]

    operations = [
        migrations.CreateModel(
            name="EncryptedClient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateField(auto_now_add=True)),
                ("last_edited", models.DateTimeField(auto_now_add=True)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("name", models.BinaryField(null=True)),
                ("note", models.BinaryField(null=True)),
                ("phone_number", models.BinaryField(null=True)),
                ("encrypted_client_key", models.BinaryField(null=True)),
                (
                    "from_rlc",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="e_client_from_rlc",
                        to="core.org",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
            bases=(core.seedwork.encryption.EncryptedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="OriginCountry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("st", "safe third country"),
                            ("ot", "other third country"),
                            ("so", "safe country"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
            options={
                "verbose_name": "OriginCountry",
                "verbose_name_plural": "OriginCountries",
            },
        ),
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(blank=True, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "RecordQuestionnaire",
                "verbose_name_plural": "RecordQuestionnaires",
            },
        ),
        migrations.CreateModel(
            name="QuestionnaireTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Questionnaire",
                "verbose_name_plural": "Questionnaire",
            },
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "old_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="core.encryptedclient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Record",
                "verbose_name_plural": "Records",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="RecordTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "show",
                    models.JSONField(
                        default=core.records.models.record.get_default_show
                    ),
                ),
                (
                    "rlc",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordtemplates",
                        to="core.org",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordTemplate",
                "verbose_name_plural": "RecordTemplates",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "rlc",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="core.org",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["rlc", "name"],
            },
        ),
        migrations.CreateModel(
            name="RecordUsersField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("order", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("share_keys", models.BooleanField(default=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.group",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users_fields",
                        to="core.recordtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordUsersField",
                "verbose_name_plural": "RecordUsersFields",
            },
        ),
        migrations.CreateModel(
            name="RecordStatisticField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("order", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("options", models.JSONField(default=list)),
                ("helptext", models.CharField(max_length=1000)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistic_fields",
                        to="core.recordtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordStatisticField",
                "verbose_name_plural": "RecordStatisticFields",
            },
        ),
        migrations.CreateModel(
            name="RecordStateField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("order", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("options", models.JSONField(default=list)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_fields",
                        to="core.recordtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordStateField",
                "verbose_name_plural": "RecordStateFields",
            },
        ),
        migrations.CreateModel(
            name="RecordStandardField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("order", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("TEXTAREA", "Multi Line"),
                            ("TEXT", "Single Line"),
                            ("DATETIME-LOCAL", "Date and Time"),
                            ("DATE", "Date"),
                        ],
                        default="TEXT",
                        max_length=20,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standard_fields",
                        to="core.recordtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordStandardField",
                "verbose_name_plural": "RecordStandardFields",
            },
        ),
        migrations.CreateModel(
            name="RecordSelectField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("order", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("options", models.JSONField(default=list)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="select_fields",
                        to="core.recordtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordSelectField",
                "verbose_name_plural": "RecordSelectFields",
            },
        ),
        migrations.CreateModel(
            name="RecordMultipleField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("order", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("options", models.JSONField(default=list)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multiple_fields",
                        to="core.recordtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordMultipleField",
                "verbose_name_plural": "RecordMultipleFields",
            },
        ),
        migrations.CreateModel(
            name="RecordEncryptedStandardField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("order", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("TEXTAREA", "Multi Line"),
                            ("TEXT", "Single Line"),
                            ("DATE", "Date"),
                        ],
                        default="TEXT",
                        max_length=20,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encrypted_standard_fields",
                        to="core.recordtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordEncryptedStandardField",
                "verbose_name_plural": "RecordEncryptedStandardFields",
            },
        ),
        migrations.CreateModel(
            name="RecordEncryptedSelectField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("order", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("options", models.JSONField(default=list)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encrypted_select_fields",
                        to="core.recordtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordEncryptedSelectField",
                "verbose_name_plural": "RecordEncryptedSelectFields",
            },
        ),
        migrations.CreateModel(
            name="RecordEncryptedFileField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("order", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encrypted_file_fields",
                        to="core.recordtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordEncryptedFileField",
                "verbose_name_plural": "RecordEncryptedFileFields",
            },
        ),
        migrations.CreateModel(
            name="RecordDeletion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("explanation", models.TextField()),
                ("processed", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("re", "Requested"),
                            ("gr", "Granted"),
                            ("de", "Declined"),
                        ],
                        default="re",
                        max_length=2,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processedrecorddeletions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deletions",
                        to="core.record",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requestedrecorddeletions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordDeletion",
                "verbose_name_plural": "RecordDeletions",
                "ordering": ["-state", "-created"],
            },
        ),
        migrations.CreateModel(
            name="RecordAccess",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("processed_on", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("re", "requested"),
                            ("gr", "granted"),
                            ("de", "declined"),
                        ],
                        default="re",
                        max_length=2,
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processedrecordaccesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="e_permissions_requested",
                        to="core.record",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requestedrecordaccesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordAccess",
                "verbose_name_plural": "RecordAccesses",
                "ordering": ["-state", "-created"],
            },
        ),
        migrations.AddField(
            model_name="record",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="records",
                to="core.recordtemplate",
            ),
        ),
        migrations.CreateModel(
            name="QuestionnaireTemplateFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="questionnairefile/")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="core.questionnairetemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "QuestionnaireFile",
                "verbose_name_plural": "QuestionnaireFiles",
            },
        ),
        migrations.AddField(
            model_name="questionnairetemplate",
            name="records",
            field=models.ManyToManyField(
                through="core.Questionnaire", to="core.record"
            ),
        ),
        migrations.AddField(
            model_name="questionnairetemplate",
            name="rlc",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questionnaires",
                to="core.org",
            ),
        ),
        migrations.CreateModel(
            name="QuestionnaireQuestion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[("FILE", "File"), ("TEXTAREA", "Text")], max_length=20
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="core.questionnairetemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "QuestionnaireField",
                "verbose_name_plural": "QuestionnaireFields",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuestionnaireAnswer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.BinaryField()),
                ("aes_key", models.BinaryField(default=b"")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="core.questionnairequestion",
                    ),
                ),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="core.questionnaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "QuestionnaireAnswer",
                "verbose_name_plural": "QuestionnaireAnswers",
            },
            bases=(core.seedwork.encryption.EncryptedModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questionnaires",
                to="core.record",
            ),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="questionnaires",
                to="core.questionnairetemplate",
            ),
        ),
        migrations.CreateModel(
            name="PoolRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("record_key", models.CharField(max_length=255)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.record"
                    ),
                ),
            ],
            options={
                "verbose_name": "PoolRecord",
                "verbose_name_plural": "PoolRecords",
            },
        ),
        migrations.CreateModel(
            name="PoolConsultant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PoolConsultant",
                "verbose_name_plural": "PoolConsultants",
            },
        ),
        migrations.CreateModel(
            name="EncryptedRecordMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("message", models.BinaryField()),
                (
                    "record",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.record",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="e_record_messages_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordMessage",
                "verbose_name_plural": "RecordMessages",
                "ordering": ["created"],
            },
            bases=(core.seedwork.encryption.EncryptedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="EncryptedRecordDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_edited", models.DateTimeField(auto_now_add=True)),
                ("file_size", models.BigIntegerField(null=True)),
                (
                    "key",
                    models.SlugField(
                        allow_unicode=True, max_length=1000, null=True, unique=True
                    ),
                ),
                ("exists", models.BooleanField(default=True)),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="e_record_documents_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="core.record",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordDocument",
                "verbose_name_plural": "RecordDocuments",
            },
        ),
        migrations.AddField(
            model_name="encryptedclient",
            name="origin_country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="e_clients",
                to="core.origincountry",
            ),
        ),
        migrations.CreateModel(
            name="RecordUsersEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="core.recordusersfield",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users_entries",
                        to="core.record",
                    ),
                ),
                (
                    "value",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "RecordUsersEntry",
                "verbose_name_plural": "RecordUsersEntries",
                "unique_together": {("record", "field")},
            },
        ),
        migrations.CreateModel(
            name="RecordStatisticEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("value", models.CharField(max_length=200)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="core.recordstatisticfield",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistic_entries",
                        to="core.record",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordStatisticEntry",
                "verbose_name_plural": "RecordStatisticEntries",
                "unique_together": {("record", "field")},
            },
        ),
        migrations.CreateModel(
            name="RecordStateEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("value", models.CharField(max_length=1000)),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="core.recordstatefield",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_entries",
                        to="core.record",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordStateEntry",
                "verbose_name_plural": "RecordStateEntries",
                "unique_together": {("record", "field")},
            },
        ),
        migrations.CreateModel(
            name="RecordStandardEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("value", models.TextField(max_length=20000)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="core.recordstandardfield",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standard_entries",
                        to="core.record",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordStandardEntry",
                "verbose_name_plural": "RecordStandardEntries",
                "unique_together": {("record", "field")},
            },
        ),
        migrations.CreateModel(
            name="RecordSelectEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("value", models.CharField(max_length=200)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="core.recordselectfield",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="select_entries",
                        to="core.record",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordSelectEntry",
                "verbose_name_plural": "RecordSelectEntries",
                "unique_together": {("record", "field")},
            },
        ),
        migrations.CreateModel(
            name="RecordMultipleEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("value", models.JSONField()),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="core.recordmultiplefield",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multiple_entries",
                        to="core.record",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordMultipleEntry",
                "verbose_name_plural": "RecordMultipleEntries",
                "unique_together": {("record", "field")},
            },
        ),
        migrations.CreateModel(
            name="RecordEncryptionNew",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.BinaryField()),
                ("correct", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encryptions",
                        to="core.record",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordencryptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordEncryption",
                "verbose_name_plural": "RecordEncryptions",
                "unique_together": {("user", "record")},
            },
            bases=(core.seedwork.encryption.EncryptedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="RecordEncryptedStandardEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("value", models.BinaryField()),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="core.recordencryptedstandardfield",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encrypted_standard_entries",
                        to="core.record",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordStandardEntry",
                "verbose_name_plural": "RecordStandardEntries",
                "unique_together": {("record", "field")},
            },
            bases=(
                core.records.models.record.RecordEntryEncryptedModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="RecordEncryptedSelectEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("value", models.BinaryField()),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="core.recordencryptedselectfield",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encrypted_select_entries",
                        to="core.record",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordEncryptedSelectEntry",
                "verbose_name_plural": "RecordEncryptedSelectEntries",
                "unique_together": {("record", "field")},
            },
            bases=(
                core.records.models.record.RecordEntryEncryptedModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="RecordEncryptedFileEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        upload_to="recordmanagement/recordencryptedfileentry/"
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="core.recordencryptedfilefield",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encrypted_file_entries",
                        to="core.record",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordEncryptedFileEntry",
                "verbose_name_plural": "RecordEncryptedFileEntries",
                "unique_together": {("record", "field")},
            },
        ),
    ]
