# Generated by Django 5.0.8 on 2024-12-05 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0124_todo_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="assignee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignee",
                to="core.orguser",
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creator",
                to="core.orguser",
            ),
        ),
    ]
