# Generated by Django 5.1.3 on 2025-01-14 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0125_alter_todo_assignee_alter_todo_creator"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Todo",
            new_name="Task",
        ),
    ]
