# Generated by Django 5.0.8 on 2025-02-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0126_rename_todo_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
