# Generated by Django 4.0.7 on 2022-10-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0127_remove_encryptedrecorddocument_creator"),
    ]

    operations = [
        migrations.RenameField(
            model_name="encryptedrecordmessage",
            old_name="sender",
            new_name="sender_old",
        ),
    ]
