# Generated by Django 5.1.4 on 2025-02-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0128_alter_task_deadline_alter_task_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomSession",
            fields=[
                (
                    "session_key",
                    models.CharField(
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                        verbose_name="session key",
                    ),
                ),
                ("session_data", models.TextField(verbose_name="session data")),
                (
                    "expire_date",
                    models.DateTimeField(db_index=True, verbose_name="expire date"),
                ),
                ("user_id", models.IntegerField(db_index=True, null=True)),
            ],
            options={
                "verbose_name": "session",
                "verbose_name_plural": "sessions",
                "abstract": False,
            },
        ),
    ]
