# Generated by Django 5.1.6 on 2025-03-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0129_customsession_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="collabdocument",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="collabdocument",
            name="rlc",
        ),
        migrations.RemoveField(
            model_name="permissionforcollabdocument",
            name="document",
        ),
        migrations.RemoveField(
            model_name="permissionforcollabdocument",
            name="permission",
        ),
        migrations.AlterUniqueTogether(
            name="permissionforcollabdocument",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="permissionforcollabdocument",
            name="group_has_permission",
        ),
        migrations.DeleteModel(
            name="TextDocumentVersion",
        ),
        migrations.DeleteModel(
            name="CollabDocument",
        ),
        migrations.DeleteModel(
            name="CollabPermission",
        ),
        migrations.DeleteModel(
            name="PermissionForCollabDocument",
        ),
    ]
