# Generated by Django 5.1.6 on 2025-03-04 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0130_alter_collabdocument_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orguser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
