# Generated by Django 5.1.3 on 2025-03-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0131_alter_orguser_user_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
