# Generated by Django 5.1.6 on 2025-03-06 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0133_alter_article_options_alter_collab_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customsession",
            options={
                "verbose_name": "AUT_CustomSession",
                "verbose_name_plural": "AUT_CustomSessions",
            },
        ),
    ]
