# Generated by Django 5.1.7 on 2025-03-11 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0134_alter_customsession_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="from_rlc",
            new_name="org",
        ),
        migrations.AddField(
            model_name="org",
            name="default_group_for_new_users",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_group_for_new_users",
                to="core.group",
            ),
        ),
    ]
