# Generated by Django 5.1.7 on 2025-03-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0137_note_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={
                "ordering": ["-order"],
                "verbose_name": "ORG_Note",
                "verbose_name_plural": "ORG_Notes",
            },
        ),
    ]
