# Generated by Django 5.1.7 on 2025-03-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0138_alter_note_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="is_chat_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="org",
            name="is_events_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="org",
            name="is_mail_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
