# Generated by Django 5.1.7 on 2025-03-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0139_org_is_chat_enabled_org_is_events_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="is_wide",
            field=models.BooleanField(default=False),
        ),
    ]
