# Generated by danielmoessner on 2022-10-27 15:07

from django.db import migrations


def create_fixtures(apps, schema_editor):
    from core.fixtures import (
        create_collab_permissions,
        create_folder_permissions,
        create_permissions,
    )

    Permission = apps.get_model("core", "Permission")
    create_permissions(Permission)

    CollabPermission = apps.get_model("core", "CollabPermission")
    create_collab_permissions(CollabPermission)

    FolderPermission = apps.get_model("core", "FolderPermission")
    create_folder_permissions(FolderPermission)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0140_legalrequirement_accept_text_and_more"),
    ]

    operations = [
        migrations.RunPython(create_fixtures),
    ]
