# Generated by Django 5.1.7 on 2025-03-20 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0140_note_is_wide"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roadmapitem",
            options={
                "ordering": ["-date"],
                "verbose_name": "INT_RoadmapItem",
                "verbose_name_plural": "INT_RoadmapItems",
            },
        ),
    ]
