# Generated by Django 4.1.2 on 2022-10-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0119_matrixuser"),
        ("core", "0140_legalrequirement_accept_text_and_more"),
    ]

    operations = []
