# Generated by Django 4.1.2 on 2022-10-27 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0141_create_fixtures"),
        ("core", "0141_merge_20221024_1325"),
    ]

    operations = []
