# Generated by Django 5.1.7 on 2025-03-27 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0141_alter_roadmapitem_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="rlc",
            new_name="org",
        ),
    ]
