# Generated by Django 5.1.7 on 2025-03-27 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0142_rename_rlc_note_org"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datasheettemplate",
            old_name="rlc",
            new_name="org",
        ),
    ]
