# Generated by Django 4.1.2 on 2022-10-31 11:47

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0143_alter_legalrequirementuser_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200, unique=True)),
                ("relative_path", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Domain",
                "verbose_name_plural": "Domains",
            },
        ),
        migrations.CreateModel(
            name="MailUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("user", models.UUIDField(unique=True)),
                ("pw_hash", models.CharField(max_length=1000)),
                ("relative_path", models.CharField(max_length=100)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.domain"
                    ),
                ),
            ],
            options={
                "verbose_name": "MailUser",
                "verbose_name_plural": "MailUsers",
                "unique_together": {("domain", "relative_path")},
            },
        ),
        migrations.CreateModel(
            name="Alias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("localpart", models.CharField(db_index=True, max_length=100)),
                ("is_default", models.BooleanField(db_index=True, default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="core.mailuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alias",
                "verbose_name_plural": "Aliases",
                "unique_together": {("user", "localpart")},
            },
        ),
    ]
