# Generated by Django 5.1.7 on 2025-03-27 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0143_rename_rlc_datasheettemplate_org"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasheettemplate",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recordtemplates",
                to="core.org",
            ),
        ),
    ]
