# Generated by Django 4.1.2 on 2022-11-06 11:21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0143_alter_legalrequirementuser_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="rlcuser",
            name="calendar_uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
