# Generated by Django 4.1.2 on 2022-11-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0144_foldersfolder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foldersfolder",
            name="org_pk",
            field=models.IntegerField(null=True),
        ),
    ]
