# Generated by Django 5.1.7 on 2025-03-30 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0144_alter_datasheettemplate_org"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questionnairetemplate",
            old_name="rlc",
            new_name="org",
        ),
    ]
