# Generated by Django 4.1.2 on 2022-11-06 11:22
import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    RlcUser = apps.get_model("core", "RlcUser")
    for row in RlcUser.objects.all():
        row.calendar_uuid = uuid.uuid4()
        row.save(update_fields=["calendar_uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0144_rlcuser_calendar_uuid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop)
    ]
