# Generated by Django 5.1.7 on 2025-03-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0145_rename_rlc_questionnairetemplate_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="user_qualifications",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
