# Generated by Django 4.1.2 on 2022-11-06 11:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0145_auto_20221106_1222"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rlcuser",
            name="calendar_uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
