# Generated by Django 5.1.7 on 2025-03-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0146_org_user_qualifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="orguser",
            name="additional_information",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="orguser",
            name="qualifications",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
