# Generated by Django 4.1.2 on 2022-11-10 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0146_rlcuser_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foldersfolder",
            name="parent",
        ),
        migrations.AddField(
            model_name="foldersfolder",
            name="_parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.foldersfolder",
            ),
        ),
    ]
