# Generated by Django 5.1.7 on 2025-06-04 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0147_orguser_additional_information_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="recordsview",
            name="records_view_one_of_both_is_set",
        ),
    ]
