# Generated by Django 4.1.2 on 2022-11-10 11:27

import uuid

from django.db import migrations, models


def create_unique_slug(apps, schema_editor):
    RlcUser = apps.get_model("core", "RlcUser")

    users = list(RlcUser.objects.all())
    for e in users:
        e.slug = uuid.uuid4()

    RlcUser.objects.bulk_update(users, fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0147_remove_foldersfolder_parent_foldersfolder__parent"),
    ]

    operations = [
        migrations.RunPython(create_unique_slug),
        migrations.AlterField(
            model_name="rlcuser",
            name="slug",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
