# Generated by Django 4.1.3 on 2022-11-11 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0144_meta_org_meta"),
        ("core", "0148_alter_rlcuser_slug"),
    ]

    operations = []
