# Generated by Django 5.1.7 on 2025-06-04 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0148_remove_recordsview_records_view_one_of_both_is_set"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recordsview",
            options={
                "ordering": ["ordering"],
                "verbose_name": "REC_RecordsView",
                "verbose_name_plural": "REC_RecordsViews",
            },
        ),
    ]
