# Generated by Django 5.1.8 on 2026-01-01 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0149_alter_recordsview_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keyring",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.JSONField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keyring",
                        to="core.orguser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupKey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.JSONField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_keys",
                        to="core.group",
                    ),
                ),
                (
                    "keyring",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_keys",
                        to="core.keyring",
                    ),
                ),
            ],
            options={
                "unique_together": {("keyring", "group")},
            },
        ),
        migrations.CreateModel(
            name="ObjectKey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.UUIDField()),
                ("object_type", models.CharField(max_length=100)),
                ("key", models.JSONField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="object_keys",
                        to="core.group",
                    ),
                ),
                (
                    "keyring",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="object_keys",
                        to="core.keyring",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("keyring__isnull", False), ("group__isnull", True)
                            ),
                            models.Q(
                                ("keyring__isnull", True), ("group__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="one_of_both_is_set_object_key",
                    )
                ],
                "unique_together": {("keyring", "object_id", "object_type")},
            },
        ),
    ]
