# Generated by Django 5.1.8 on 2026-01-04 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0149_alter_recordsview_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keyring",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.JSONField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keyring",
                        to="core.orguser",
                    ),
                ),
            ],
            options={
                "verbose_name": "ENC_Keyring",
                "verbose_name_plural": "ENC_Keyrings",
            },
        ),
        migrations.CreateModel(
            name="GroupKey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.JSONField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_keys",
                        to="core.group",
                    ),
                ),
                (
                    "keyring",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_keys",
                        to="core.keyring",
                    ),
                ),
            ],
            options={
                "verbose_name": "ENC_GroupKey",
                "verbose_name_plural": "ENC_GroupKeys",
                "unique_together": {("keyring", "group")},
            },
        ),
    ]
