# Generated by Django 4.1.3 on 2022-11-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0146_auto_20221106_1222"),
        ("core", "0149_merge_0144_meta_org_meta_0148_alter_rlcuser_slug"),
    ]

    operations = []
