# Generated by Django 5.1.8 on 2026-01-05 14:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0150_keyring_groupkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupkey",
            name="is_invalidated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="keyring",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="keyring",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
