# Generated by Django 4.1.3 on 2022-11-12 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0150_merge_20221112_1740"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="meta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.meta",
            ),
        ),
    ]
