# Generated by Django 4.1.3 on 2022-11-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0144_domain_mailuser_alias"),
        ("core", "0151_alter_org_meta"),
    ]

    operations = []
