# Generated by Django 5.2.11 on 2026-02-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0151_groupkey_is_invalidated_keyring_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loggedpath",
            name="path",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="loggedpath",
            name="time",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
