# Generated by Django 4.1.3 on 2022-11-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0152_merge_0144_domain_mailuser_alias_0151_alter_org_meta"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mailuser",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="domain",
            name="users",
            field=models.ManyToManyField(related_name="domains", to="core.mailuser"),
        ),
        migrations.RemoveField(
            model_name="mailuser",
            name="domain",
        ),
    ]
