# Generated by Django 5.2.11 on 2026-03-03 11:35

from django.db import migrations, models


def set_statistic_fields_required(apps, schema_editor):
    DataSheetStatisticField = apps.get_model("core", "DataSheetStatisticField")
    DataSheetStatisticField.objects.all().update(is_required=True)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0152_alter_loggedpath_path_alter_loggedpath_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasheetencryptedfilefield",
            name="is_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="datasheetencryptedselectfield",
            name="is_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="datasheetencryptedstandardfield",
            name="is_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="datasheetmultiplefield",
            name="is_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="datasheetselectfield",
            name="is_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="datasheetstandardfield",
            name="is_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="datasheetstatefield",
            name="is_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="datasheetstatisticfield",
            name="is_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="datasheetusersfield",
            name="is_required",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            set_statistic_fields_required,
            migrations.RunPython.noop,
        ),
    ]
