# Generated by Django 5.2.12 on 2026-03-21 10:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def migrate_assignee_to_assignees(apps, schema_editor):
    Task = apps.get_model("core", "Task")
    for task in Task.objects.select_related("assignee").all():
        if task.assignee_id is not None:
            task.assignees.add(task.assignee_id)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0153_datasheetencryptedfilefield_is_required_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="assignees",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_tasks", to="core.orguser"
            ),
        ),
        migrations.RunPython(migrate_assignee_to_assignees, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="task",
            name="assignee",
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="progress",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_tasks",
                to="core.orguser",
            ),
        ),
    ]
