# Generated by Django 4.1.3 on 2022-11-17 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0153_alter_mailuser_unique_together_domain_users_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailOrg",
            fields=[
                (
                    "id",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
            ],
            options={
                "verbose_name": "MailOrg",
                "verbose_name_plural": "MailOrgs",
            },
        ),
        migrations.RemoveField(
            model_name="domain",
            name="users",
        ),
        migrations.AddField(
            model_name="alias",
            name="domain",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aliases",
                to="core.domain",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="domain",
            name="org",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domains",
                to="core.mailorg",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mailuser",
            name="org",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="core.mailorg",
            ),
            preserve_default=False,
        ),
    ]
