# Generated by Django 4.1.3 on 2022-11-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0154_mailorg_remove_domain_users_alias_domain_domain_org_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Domain",
            new_name="MailDomain",
        ),
    ]
