# Generated by Django 4.1.3 on 2022-11-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0155_rename_domain_maildomain"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Alias",
            new_name="MailAlias",
        ),
    ]
