# Generated by Django 5.2.12 on 2026-03-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0155_migrate_is_done_to_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="comments",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
