# Generated by Django 5.2.12 on 2026-03-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0156_task_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
