# Generated by Django 4.1.3 on 2022-11-17 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0156_rename_alias_mailalias"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailuser",
            name="user",
        ),
        migrations.AddField(
            model_name="mailuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
    ]
