# Generated by Django 4.1.3 on 2022-11-17 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0157_alter_mailuser_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailuser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mail_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
