# Generated by Django 5.2.12 on 2026-03-26 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0157_task_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventsevent",
            name="is_global",
        ),
    ]
