# Generated by Django 5.2.12 on 2026-03-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0158_remove_eventsevent_is_global"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="recipients",
            field=models.ManyToManyField(
                blank=True,
                help_text="The organizations that should receive this article. If empty, all organizations will receive it.",
                related_name="recipients",
                to="core.org",
            ),
        ),
    ]
