# Generated by Django 4.1.3 on 2022-11-17 15:28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0158_alter_mailuser_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="mailorg",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.CreateModel(
            name="MailAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("relative_path", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to="core.mailgroup",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to="core.mailuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "MailAccount",
                "verbose_name_plural": "MailAccounts",
            },
        ),
        migrations.AddConstraint(
            model_name="mailaccount",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("group__isnull", True), ("user__isnull", False)),
                    models.Q(("group__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="one_of_both_is_set",
            ),
        ),
    ]
