# Generated by Django 5.2.12 on 2026-03-26 15:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0158_remove_eventsevent_is_global"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("APPOINTMENT", "Appointment"),
                            ("TASK", "Task"),
                            ("MEETING", "Meeting"),
                            ("DEADLINE", "Deadline"),
                            ("EXTERNAL", "External"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, default="", max_length=500)),
                (
                    "recurrence_rule",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("recurrence_until", models.DateField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="core.orguser",
                    ),
                ),
            ],
            options={
                "verbose_name": "EVT_CalendarEvent",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="CalendarEventAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="calendar/attachments/")),
                ("name", models.CharField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="core.calendarevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "EVT_CalendarEventAttachment",
            },
        ),
        migrations.CreateModel(
            name="CalendarEventGuest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attendance_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guests",
                        to="core.calendarevent",
                    ),
                ),
                (
                    "org_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_events",
                        to="core.orguser",
                    ),
                ),
            ],
            options={
                "verbose_name": "EVT_CalendarEventGuest",
                "unique_together": {("event", "org_user")},
            },
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="guest_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="guest_at_events",
                through="core.CalendarEventGuest",
                to="core.orguser",
            ),
        ),
    ]
