# Generated by Django 5.2.12 on 2026-03-26 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0159_calendarevent_calendareventattachment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="org",
            name="collab_migrated",
        ),
    ]
