# Generated by Django 4.1.3 on 2022-11-17 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0159_mailgroup_alter_mailorg_id_mailaccount_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailgroup",
            options={"verbose_name": "MailGroup", "verbose_name_plural": "MailGroups"},
        ),
    ]
