# Generated by Django 4.1.3 on 2022-11-17 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0160_alter_mailgroup_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MailAlias",
            new_name="MailAddress",
        ),
    ]
