# Generated by Django 4.1.3 on 2022-11-17 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0161_rename_mailalias_mailaddress"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mailaddress",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="mailaddress",
            name="account",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aliases",
                to="core.mailaccount",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="mailaddress",
            name="user",
        ),
    ]
