# Generated by Django 5.2.12 on 2026-04-15 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0161_article_recipients"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="description",
            new_name="preview",
        ),
    ]
