# Generated by Django 5.2.13 on 2026-06-03 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0162_rename_article_description_to_preview"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventsevent",
            options={
                "ordering": ["start_time"],
                "verbose_name": "EVT_EventsEvent",
                "verbose_name_plural": "EVT_EventsEvents",
            },
        ),
        migrations.AlterField(
            model_name="eventsevent",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="core.org",
            ),
        ),
    ]
