# Generated by Django 6.0.5 on 2026-06-04 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0163_alter_eventsevent_options_alter_eventsevent_org"),
        ("core", "0163_orguser_last_activity"),
    ]

    operations = []
