# Generated by Django 4.1.3 on 2022-11-17 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0163_remove_maildomain_relative_path_mailgroup_members_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailaccount",
            name="group",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account",
                to="core.mailgroup",
            ),
        ),
        migrations.AlterField(
            model_name="mailaccount",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account",
                to="core.mailuser",
            ),
        ),
    ]
