# Generated by Django 6.0.5 on 2026-06-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0164_merge_20260604_1215"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="is_all_day",
            field=models.BooleanField(default=False),
        ),
    ]
