# Generated by Django 4.1.3 on 2022-11-17 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0165_remove_mailuser_relative_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailgroup",
            name="org",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="core.mailorg",
            ),
            preserve_default=False,
        ),
    ]
