# Generated by Django 6.0.5 on 2026-06-22

import django.db.models.deletion
from django.db import migrations, models


def migrate_event_shares_forward(apps, schema_editor):
    CalendarEvent = apps.get_model("core", "CalendarEvent")
    CalendarEventGuest = apps.get_model("core", "CalendarEventGuest")
    CalendarEventShare = apps.get_model("core", "CalendarEventShare")

    event_to_creator = dict(CalendarEvent.objects.values_list("id", "creator_id"))

    for event_id, creator_id in event_to_creator.items():
        CalendarEventShare.objects.get_or_create(
            event_id=event_id,
            shared_user_id=creator_id,
            defaults={
                "access_level": "ADMIN",
                "granted_by_id": creator_id,
            },
        )

    for guest in CalendarEventGuest.objects.all().iterator():
        CalendarEventShare.objects.get_or_create(
            event_id=guest.event_id,
            shared_user_id=guest.org_user_id,
            defaults={
                "access_level": "VIEW",
                "granted_by_id": event_to_creator.get(guest.event_id),
            },
        )


def migrate_event_shares_backward(apps, schema_editor):
    CalendarEventGuest = apps.get_model("core", "CalendarEventGuest")
    CalendarEventShare = apps.get_model("core", "CalendarEventShare")

    user_shares = CalendarEventShare.objects.filter(
        shared_user_id__isnull=False,
        access_level="VIEW",
    ).exclude(event__creator_id=models.F("shared_user_id"))

    for share in user_shares.iterator():
        CalendarEventGuest.objects.get_or_create(
            event_id=share.event_id,
            org_user_id=share.shared_user_id,
            defaults={"attendance_status": "PENDING"},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0165_calendarevent_is_all_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEventShare",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("VIEW", "View"),
                            ("EDIT", "Edit"),
                            ("ADMIN", "Admin"),
                        ],
                        default="VIEW",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="core.calendarevent",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_calendar_event_shares",
                        to="core.orguser",
                    ),
                ),
                (
                    "shared_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_event_group_shares",
                        to="core.group",
                    ),
                ),
                (
                    "shared_org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_event_org_shares",
                        to="core.org",
                    ),
                ),
                (
                    "shared_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_event_user_shares",
                        to="core.orguser",
                    ),
                ),
            ],
            options={
                "verbose_name": "EVT_CalendarEventShare",
            },
        ),
        migrations.AddConstraint(
            model_name="calendareventshare",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        shared_user__isnull=False,
                        shared_group__isnull=True,
                        shared_org__isnull=True,
                    )
                    | models.Q(
                        shared_user__isnull=True,
                        shared_group__isnull=False,
                        shared_org__isnull=True,
                    )
                    | models.Q(
                        shared_user__isnull=True,
                        shared_group__isnull=True,
                        shared_org__isnull=False,
                    )
                ),
                name="calendar_share_exactly_one_principal",
            ),
        ),
        migrations.AddConstraint(
            model_name="calendareventshare",
            constraint=models.UniqueConstraint(
                condition=models.Q(shared_user__isnull=False),
                fields=("event", "shared_user"),
                name="calendar_share_unique_event_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="calendareventshare",
            constraint=models.UniqueConstraint(
                condition=models.Q(shared_group__isnull=False),
                fields=("event", "shared_group"),
                name="calendar_share_unique_event_group",
            ),
        ),
        migrations.AddConstraint(
            model_name="calendareventshare",
            constraint=models.UniqueConstraint(
                condition=models.Q(shared_org__isnull=False),
                fields=("event", "shared_org"),
                name="calendar_share_unique_event_org",
            ),
        ),
        migrations.AddIndex(
            model_name="calendareventshare",
            index=models.Index(
                fields=["event", "shared_user"],
                name="cal_share_user_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="calendareventshare",
            index=models.Index(
                fields=["event", "shared_group"],
                name="cal_share_group_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="calendareventshare",
            index=models.Index(
                fields=["event", "shared_org"],
                name="cal_share_org_idx",
            ),
        ),
        migrations.RunPython(
            migrate_event_shares_forward,
            migrate_event_shares_backward,
        ),
        migrations.RemoveField(
            model_name="calendarevent",
            name="guest_users",
        ),
        migrations.DeleteModel(
            name="CalendarEventGuest",
        ),
    ]
