# Generated by Django 6.0.5 on 2026-06-30 13:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0166_calendareventshare_acl"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="calendareventshare",
            name="calendar_share_exactly_one_principal",
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="end_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="calendareventshare",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("shared_user__isnull", False),
                        ("shared_group__isnull", True),
                        ("shared_org__isnull", True),
                    ),
                    models.Q(
                        ("shared_user__isnull", True),
                        ("shared_group__isnull", False),
                        ("shared_org__isnull", True),
                    ),
                    models.Q(
                        ("shared_user__isnull", True),
                        ("shared_group__isnull", True),
                        ("shared_org__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="calendar_share_exactly_one_principal",
            ),
        ),
    ]
