# Generated by Django 4.1.3 on 2022-11-18 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0166_mailgroup_org"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maildomain",
            name="org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domains",
                to="core.mailorg",
            ),
        ),
    ]
