# Generated by Django 4.1.3 on 2022-11-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0167_alter_maildomain_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="rlcuser",
            name="key",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
