# Generated by Django 6.0.5 on 2026-07-01 12:33

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0168_userprofile_previous_login"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEventReminder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("minutes_before", models.PositiveIntegerField(default=0)),
                (
                    "method",
                    models.CharField(
                        choices=[("EMAIL", "Email"), ("PUSH", "Push")], max_length=20
                    ),
                ),
                ("remind_at", models.DateTimeField()),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="core.calendarevent",
                    ),
                ),
                (
                    "org_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_event_reminders",
                        to="core.orguser",
                    ),
                ),
            ],
            options={
                "verbose_name": "EVT_CalendarEventReminder",
                "indexes": [
                    models.Index(
                        fields=["remind_at", "dispatched_at"],
                        name="cal_reminder_due_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "org_user", "method", "minutes_before"),
                        name="calendar_reminder_unique_per_user_method_offset",
                    )
                ],
            },
        ),
    ]
