# Generated by Django 4.1.3 on 2022-11-29 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0168_rlcuser_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailaddress",
            name="account",
        ),
        migrations.RemoveField(
            model_name="mailaddress",
            name="domain",
        ),
        migrations.RemoveField(
            model_name="maildomain",
            name="org",
        ),
        migrations.RemoveField(
            model_name="mailgroup",
            name="members",
        ),
        migrations.RemoveField(
            model_name="mailgroup",
            name="org",
        ),
        migrations.RemoveField(
            model_name="mailuser",
            name="org",
        ),
        migrations.RemoveField(
            model_name="mailuser",
            name="user",
        ),
        migrations.DeleteModel(
            name="MailAccount",
        ),
        migrations.DeleteModel(
            name="MailAddress",
        ),
        migrations.DeleteModel(
            name="MailDomain",
        ),
        migrations.DeleteModel(
            name="MailGroup",
        ),
        migrations.DeleteModel(
            name="MailOrg",
        ),
        migrations.DeleteModel(
            name="MailUser",
        ),
    ]
