# Generated by Django 4.1.3 on 2022-11-21 15:23

import django.db.models.deletion
from django.db import migrations, models

import core.folders.domain.aggregates.upgrade


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0168_record_upgrade_pk"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordUpgrade",
            fields=[
                (
                    "id",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                ("org_pk", models.IntegerField()),
                ("folder_pk", models.UUIDField()),
            ],
            options={
                "verbose_name": "RecordUpgrade",
                "verbose_name_plural": "RecordUpgrades",
            },
            bases=(core.folders.domain.aggregates.upgrade.Upgrade, models.Model),
        ),
        migrations.RemoveField(
            model_name="record",
            name="upgrade_pk",
        ),
        migrations.AddField(
            model_name="record",
            name="upgrade",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="core.recordupgrade",
            ),
        ),
    ]
