# Generated by Django 4.1.3 on 2022-11-29 13:05

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0168_rlcuser_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailAdmin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin",
                        to="core.mailuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "MailAdmin",
                "verbose_name_plural": "MailAdmins",
            },
        ),
    ]
