# Generated by Django 4.1.3 on 2022-11-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0169_recordupgrade_remove_record_upgrade_pk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="key",
            field=models.JSONField(null=True),
        ),
    ]
