# Generated by Django 6.0.5 on 2026-07-09 15:46

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0169_calendareventreminder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendareventreminder",
            name="method",
            field=models.CharField(
                choices=[("EMAIL", "Email"), ("IN_APP", "In-app")], max_length=20
            ),
        ),
        migrations.CreateModel(
            name="CalendarNotification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("message", models.CharField(max_length=500)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.calendarevent",
                    ),
                ),
                (
                    "org_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_notifications",
                        to="core.orguser",
                    ),
                ),
            ],
            options={
                "verbose_name": "EVT_CalendarNotification",
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["org_user", "read_at"],
                        name="cal_notification_inbox_idx",
                    )
                ],
            },
        ),
    ]
