# Generated by Django 4.1.3 on 2022-11-29 13:41

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0169_remove_mailaddress_account_remove_mailaddress_domain_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("relative_path", models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
            options={
                "verbose_name": "MailAccount",
                "verbose_name_plural": "MailAccounts",
            },
        ),
        migrations.CreateModel(
            name="MailOrg",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
            ],
            options={
                "verbose_name": "MailOrg",
                "verbose_name_plural": "MailOrgs",
            },
        ),
        migrations.AddField(
            model_name="matrixuser",
            name="matrix_id",
            field=models.CharField(
                default=None, editable=False, max_length=8, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="matrixuser",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="MailUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("pw_hash", models.CharField(max_length=1000)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="core.mailorg",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mail_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MailUser",
                "verbose_name_plural": "MailUsers",
            },
        ),
        migrations.CreateModel(
            name="MailGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "members",
                    models.ManyToManyField(related_name="groups", to="core.mailuser"),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="core.mailorg",
                    ),
                ),
            ],
            options={
                "verbose_name": "MailGroup",
                "verbose_name_plural": "MailGroups",
            },
        ),
        migrations.CreateModel(
            name="MailDomain",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("name", models.CharField(db_index=True, max_length=200, unique=True)),
                (
                    "org",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="core.mailorg",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domain",
                "verbose_name_plural": "Domains",
            },
        ),
        migrations.CreateModel(
            name="MailAdmin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admin",
                        to="core.mailuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "MailAdmin",
                "verbose_name_plural": "MailAdmins",
            },
        ),
        migrations.CreateModel(
            name="MailAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("localpart", models.CharField(db_index=True, max_length=100)),
                ("is_default", models.BooleanField(db_index=True, default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="core.mailaccount",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="core.maildomain",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alias",
                "verbose_name_plural": "Aliases",
            },
        ),
        migrations.AddField(
            model_name="mailaccount",
            name="group",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account",
                to="core.mailgroup",
            ),
        ),
        migrations.AddField(
            model_name="mailaccount",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account",
                to="core.mailuser",
            ),
        ),
        migrations.AddConstraint(
            model_name="mailaccount",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("group__isnull", True), ("user__isnull", False)),
                    models.Q(("group__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="one_of_both_is_set",
            ),
        ),
    ]
