# Generated by Django 4.1.3 on 2022-11-29 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0169_mailadmin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailadmin",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="admin",
                to="core.mailuser",
            ),
        ),
    ]
