# Generated by Django 4.1.3 on 2022-11-29 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0170_mailaccount_mailorg_matrixuser_matrix_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rlcuser",
            old_name="private_key",
            new_name="old_private_key",
        ),
        migrations.RenameField(
            model_name="rlcuser",
            old_name="public_key",
            new_name="old_public_key",
        ),
    ]
