# Generated by Django 4.1.3 on 2022-11-21 15:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0170_record_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordupgrade",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
