# Generated by Django 4.1.3 on 2022-11-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0170_alter_mailadmin_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mailaccount",
            old_name="id",
            new_name="uuid",
        ),
        migrations.RenameField(
            model_name="mailaddress",
            old_name="id",
            new_name="uuid",
        ),
        migrations.RenameField(
            model_name="maildomain",
            old_name="id",
            new_name="uuid",
        ),
        migrations.RenameField(
            model_name="mailgroup",
            old_name="id",
            new_name="uuid",
        ),
        migrations.RenameField(
            model_name="mailorg",
            old_name="id",
            new_name="uuid",
        ),
        migrations.RenameField(
            model_name="mailuser",
            old_name="id",
            new_name="uuid",
        ),
    ]
