# Generated by Django 6.0.5 on 2026-07-16 16:54

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0170_alter_calendareventreminder_method_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEventOccurrenceOverride",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("original_start", models.DateTimeField()),
                ("cancelled", models.BooleanField(default=False)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=500, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occurrence_overrides",
                        to="core.calendarevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "EVT_CalendarEventOccurrenceOverride",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "original_start"),
                        name="calendar_override_unique_per_occurrence",
                    )
                ],
            },
        ),
        migrations.RemoveIndex(
            model_name="calendareventreminder",
            name="cal_reminder_due_idx",
        ),
        migrations.RemoveField(
            model_name="calendareventreminder",
            name="dispatched_at",
        ),
        migrations.AddField(
            model_name="calendareventreminder",
            name="original_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="calendareventreminder",
            name="remind_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="calendareventreminder",
            index=models.Index(fields=["remind_at"], name="cal_reminder_due_idx"),
        ),
        migrations.AddField(
            model_name="calendarnotification",
            name="occurrence_end",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
