# Generated by Django 6.0.7 on 2026-08-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0170_alter_calendareventreminder_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailimport",
            name="sending_datetime",
            field=models.DateTimeField(),
        ),
    ]
