# Generated by Django 4.1.3 on 2022-11-29 13:13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0171_rename_id_mailaccount_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailaccount",
            name="id",
            field=models.AutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mailaccount",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
