# Generated by Django 4.1.3 on 2022-12-05 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0171_rename_private_key_rlcuser_old_private_key_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailaddress",
            options={
                "verbose_name": "MailAddress",
                "verbose_name_plural": "MailAddress",
            },
        ),
        migrations.AlterModelOptions(
            name="maildomain",
            options={
                "verbose_name": "MailDomain",
                "verbose_name_plural": "MailDomains",
            },
        ),
    ]
