# Generated by Django 4.1.3 on 2022-11-23 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0171_alter_recordupgrade_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="foldersfolder",
            name="deleted",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="foldersfolder",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="foldersfolder",
            name="_parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.foldersfolder",
            ),
        ),
        migrations.AlterField(
            model_name="foldersfolder",
            name="keys",
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name="foldersfolder",
            name="org_pk",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="foldersfolder",
            name="upgrades",
            field=models.JSONField(blank=True),
        ),
    ]
