# Generated by Django 4.1.3 on 2022-11-28 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0168_rlcuser_key"),
        ("core", "0172_foldersfolder_deleted_foldersfolder_deleted_at_and_more"),
    ]

    operations = []
