# Generated by Django 4.1.3 on 2022-11-28 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0174_remove_recordupgrade_org_pk_foldersfolder_org_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foldersfolder",
            name="org_pk",
        ),
        migrations.RemoveField(
            model_name="recordupgrade",
            name="folder_pk",
        ),
        migrations.AlterField(
            model_name="foldersfolder",
            name="org",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folders_folders",
                to="core.org",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recordupgrade",
            name="raw_folder",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="record_upgrades",
                to="core.foldersfolder",
            ),
            preserve_default=False,
        ),
    ]
