# Generated by Django 4.1.3 on 2022-11-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0175_remove_foldersfolder_org_pk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="foldersfolder",
            name="stop_inherit",
            field=models.BooleanField(default=False),
        ),
    ]
