# Generated by Django 4.1.3 on 2022-12-05 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0172_alter_mailaddress_options_alter_maildomain_options"),
        ("core", "0176_foldersfolder_stop_inherit"),
    ]

    operations = []
