# Generated by Django 4.1.3 on 2022-12-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0177_merge_20221205_1310"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rlcuser",
            old_name="slug",
            new_name="uuid",
        ),
    ]
