# Generated by Django 4.1.3 on 2022-12-05 12:34

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0179_foldersfolder_uuid_recordupgrade_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foldersfolder",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="rlcuser",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
