# Generated by Django 4.1.3 on 2022-12-06 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0180_alter_foldersfolder_uuid_alter_rlcuser_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="raw_folder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="core.foldersfolder",
            ),
        ),
    ]
