# Generated by Django 4.1.3 on 2022-12-06 10:33

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0183_auto_20221206_1133"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
