# Generated by Django 4.1.3 on 2022-12-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0184_auto_20221206_1133"),
    ]

    operations = [
        migrations.AddField(
            model_name="foldersfolder",
            name="items",
            field=models.JSONField(blank=True, default=[]),
            preserve_default=False,
        ),
    ]
