# Generated by Django 4.1.3 on 2022-12-06 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0186_alter_record_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foldersfolder",
            name="upgrades",
        ),
        migrations.RemoveField(
            model_name="record",
            name="upgrade",
        ),
        migrations.DeleteModel(
            name="RecordUpgrade",
        ),
    ]
