# Generated by Django 4.1.3 on 2022-12-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0187_remove_foldersfolder_upgrades_remove_record_upgrade_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="raw_folder",
        ),
        migrations.AddField(
            model_name="record",
            name="folder_uuid",
            field=models.UUIDField(db_index=True, null=True),
        ),
    ]
