# Generated by Django 4.1.3 on 2022-12-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0188_remove_record_raw_folder_record_folder_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="maildomain",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
