#  law&orga - record and organization management software for refugee law clinics
#  Copyright (C) 2019  Dominik Walser
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>

# Generated by Django 2.1.2 on 2019-02-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_forgotpasswordlinks_ip_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="user_record_state",
            field=models.CharField(
                choices=[
                    ("ac", "accepting"),
                    ("na", "not accepting"),
                    ("de", "depends"),
                ],
                default="ac",
                max_length=2,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_state",
            field=models.CharField(
                choices=[
                    ("ac", "active"),
                    ("ia", "inactive"),
                    ("ex", "exam"),
                    ("ab", "abroad"),
                ],
                default="ac",
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
