# Generated by Django 2.2.8 on 2020-01-04 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_encryptionkeys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryptionkeys",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="encryption_keys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
