# Generated by Django 2.2.8 on 2020-02-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_auto_20200108_1533"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
