# Generated by Django 2.2.8 on 2020-07-30 10:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_notification_ref_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
