# Generated by Django 2.2.8 on 2020-08-13 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_auto_20200812_1616"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="notificationgroup",
            name="created",
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="notificationgroup",
            name="last_activity",
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
