# Generated by Django 2.2.8 on 2020-08-13 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_auto_20200813_1317"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationgroup",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="notificationgroup",
            name="last_activity",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
