# Generated by Django 3.1.7 on 2021-03-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_auto_20210324_2136"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="missingrlckey",
            name="user",
        ),
        migrations.AddField(
            model_name="newuserrequest",
            name="after_password_forgotten",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="ForgotPasswordLinks",
        ),
        migrations.DeleteModel(
            name="MissingRlcKey",
        ),
    ]
