# Generated by Django 3.1.7 on 2021-03-30 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_merge_20210330_1127"),
        ("api", "0052_auto_20210329_1810"),
    ]

    operations = []
