# Generated by Django 3.1.6 on 2021-04-08 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20210402_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logged_paths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LoggedPath',
                'verbose_name_plural': 'LoggedPaths',
                'ordering': ['time'],
            },
        ),
    ]
