# Generated by Django 3.1.6 on 2021-04-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0057_auto_20210412_1748"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rlc",
            options={
                "ordering": ["name"],
                "verbose_name": "Rlc",
                "verbose_name_plural": "Rlcs",
            },
        ),
    ]
