# Generated by Django 3.1.6 on 2021-05-13 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0062_auto_20210513_1349"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersession",
            name="rlc",
        ),
        migrations.RemoveField(
            model_name="usersessionpath",
            name="path",
        ),
        migrations.RemoveField(
            model_name="usersessionpath",
            name="session",
        ),
        migrations.DeleteModel(
            name="UserActivityPath",
        ),
        migrations.DeleteModel(
            name="UserSession",
        ),
        migrations.DeleteModel(
            name="UserSessionPath",
        ),
    ]
