# Generated by Django 3.1.6 on 2021-06-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0065_remove_rlc_creator"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RlcSettings",
        ),
    ]
