# Generated by Django 3.1.6 on 2021-06-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0066_delete_rlcsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="rlcuser",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
    ]
