# Generated by Django 3.1.6 on 2021-10-04 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_remove_haspermission_rlc_has_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_confirmed',
        ),
    ]
