# Generated by Django 3.1.6 on 2021-10-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_auto_20211011_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='rlcuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
