# Generated by Django 3.1.6 on 2021-10-14 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0074_rlcuser_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="is_active",
        ),
    ]
