# Generated by Django 3.2.9 on 2021-12-16 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0075_remove_userprofile_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rlcuser",
            options={
                "ordering": ["user__name"],
                "verbose_name": "RlcUser",
                "verbose_name_plural": "RlcUsers",
            },
        ),
    ]
