# Generated by Django 3.2.10 on 2022-01-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0077_auto_20220109_1503"),
    ]

    operations = [
        migrations.AddField(
            model_name="rlcuser",
            name="note",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
