# Generated by Django 3.2.11 on 2022-02-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0078_rlcuser_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rlcuser",
            name="note",
            field=models.TextField(blank=True),
        ),
    ]
