# Generated by Django 3.2.11 on 2022-02-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_alter_rlcuser_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedpath',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
