# Generated by Django 3.2.11 on 2022-02-09 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_loggedpath_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rlcuser',
            options={'ordering': ['is_active', 'accepted', 'locked', 'user__name'], 'verbose_name': 'RlcUser', 'verbose_name_plural': 'RlcUsers'},
        ),
    ]
