# Generated by Django 3.2.11 on 2022-02-09 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_alter_rlcuser_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='haspermission',
            unique_together={('permission', 'user_has_permission', 'group_has_permission')},
        ),
    ]
