# Generated by Django 3.2.11 on 2022-02-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0082_alter_haspermission_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="loggedpath",
            name="data",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="loggedpath",
            name="method",
            field=models.CharField(default="UNKNOWN", max_length=20),
        ),
    ]
