# Generated by Django 3.2.12 on 2022-02-20 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0089_alter_group_from_rlc"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rlcuser",
            options={
                "ordering": ["accepted", "locked", "is_active", "user__name"],
                "verbose_name": "RlcUser",
                "verbose_name_plural": "RlcUsers",
            },
        ),
        migrations.RemoveField(
            model_name="rlcuser",
            name="rlc",
        ),
    ]
