# Generated by Django 3.2.12 on 2022-03-02 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_alter_note_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='rlc',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.rlc'),
        ),
    ]
