# Generated by Django 3.2.12 on 2022-04-01 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_statisticsuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatisticsUser',
            new_name='StatisticUser',
        ),
    ]
