# Generated by Django 3.2.14 on 2022-07-27 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_auto_20220727_2120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserEncryptionKeys',
            new_name='OldUserEncryptionKeys',
        ),
    ]
