# Generated by Django 3.1.7 on 2021-03-31 14:16

import apps.static.encryption
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recordmanagement", "0028_auto_20210331_1132"),
        ("api", "0054_auto_20210330_1721"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollabPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TextDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="text_documents_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rlc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_documents",
                        to="api.rlc",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CollabDocument",
            fields=[
                (
                    "textdocument_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="collab.textdocument",
                    ),
                ),
                ("path", models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name="TextDocumentVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_draft", models.BooleanField(default=True)),
                ("content", models.BinaryField()),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="text_document_versions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="collab.textdocument",
                    ),
                ),
            ],
            bases=(apps.static.encryption.EncryptedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="EditingRoom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        auto_created=True,
                        default=apps.static.encryption.AESEncryption.generate_secure_key,
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "room_id",
                    models.CharField(
                        auto_created=True,
                        default=1,
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collab.textdocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecordDocument",
            fields=[
                (
                    "textdocument_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="collab.textdocument",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collab_documents",
                        to="recordmanagement.encryptedrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PermissionForCollabDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_has_permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_has_collab_permission",
                        to="api.group",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_permission_for_document",
                        to="collab.collabpermission",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collab_permissions",
                        to="collab.collabdocument",
                    ),
                ),
            ],
            options={
                "unique_together": {("permission", "group_has_permission", "document")},
            },
        ),
    ]
