# Generated by Django 3.1.6 on 2021-10-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecordDocument',
        ),
    ]
