# Generated by Django 3.2.11 on 2022-02-05 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collab", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textdocumentversion",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="collab.collabdocument",
            ),
        ),
    ]
