# Generated by Django 3.1.6 on 2021-10-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0002_delete_recorddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='textdocumentversion',
            name='quill',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='textdocumentversion',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='textdocumentversion',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
