# Generated by Django 3.2.11 on 2022-02-05 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0002_alter_textdocumentversion_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabdocument',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='collabdocument',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TextDocument',
        ),
    ]
