# Generated by Django 3.1.6 on 2021-10-28 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_remove_userprofile_is_active'),
        ('collab', '0003_auto_20211024_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textdocument',
            name='rlc',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_documents', to='api.rlc'),
        ),
    ]
