# Generated by Django 3.1.6 on 2021-11-16 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collab', '0004_auto_20211028_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textdocumentversion',
            name='content',
            field=models.BinaryField(blank=True),
        ),
        migrations.AlterField(
            model_name='textdocumentversion',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text_document_versions_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
