# Generated by Django 3.2.11 on 2022-02-05 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0080_loggedpath_status"),
        ("collab", "0005_remove_textdocumentversion_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collabdocument",
            name="rlc",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collab_documents",
                to="core.rlc",
            ),
        ),
    ]
