# Generated by Django 3.2.11 on 2022-02-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collab", "0006_alter_collabdocument_rlc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collabdocument",
            name="creator",
        ),
    ]
