# Generated by Django 3.2.10 on 2022-01-15 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0006_alter_textdocument_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditingRoom',
        ),
    ]
