# Generated by Django 3.2.10 on 2022-01-15 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0007_delete_editingroom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collabdocument',
            options={'verbose_name': 'CollabDocument', 'verbose_name_plural': 'CollabDocuments'},
        ),
        migrations.AlterModelOptions(
            name='collabpermission',
            options={'verbose_name': 'CollabPermission', 'verbose_name_plural': 'CollabPermissions'},
        ),
    ]
