# Generated by Django 3.2.10 on 2022-01-15 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0008_auto_20220115_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textdocumentversion',
            options={'verbose_name': 'TextDocumentVersion', 'verbose_name_plural': 'TextDocumentVersions'},
        ),
    ]
