# Generated by Django 3.2.12 on 2022-03-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0009_alter_collabdocument_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collabdocument',
            options={'ordering': ['path'], 'verbose_name': 'CollabDocument', 'verbose_name_plural': 'CollabDocuments'},
        ),
    ]
