# Generated by Django 3.2.11 on 2022-02-05 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_rlcuser_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collab', '0009_alter_textdocumentversion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabdocument',
            name='new_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='collabdocument',
            name='new_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collab_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collabdocument',
            name='new_rlc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collab_documents', to='api.rlc'),
        ),
    ]
