# Generated by Django 3.2.11 on 2022-02-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0011_collabdocument_new_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collabdocument',
            name='new_id',
            field=models.IntegerField(),
        ),
    ]
