# Generated by Django 3.2.11 on 2022-02-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0012_alter_collabdocument_new_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collabdocument',
            name='new_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='collabdocument',
            name='textdocument_ptr',
        ),
    ]
