# Generated by Django 3.2.11 on 2022-02-05 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0013_auto_20220205_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collabdocument',
            old_name='new_id',
            new_name='id',
        ),
    ]
