# Generated by Django 3.2.11 on 2022-02-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0014_rename_new_id_collabdocument_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collabdocument',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
