# Generated by Django 3.2.11 on 2022-02-05 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0015_alter_collabdocument_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collabdocument',
            old_name='new_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='collabdocument',
            old_name='new_creator',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='collabdocument',
            old_name='new_rlc',
            new_name='rlc',
        ),
    ]
