# Generated by Django 3.1.6 on 2021-05-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0003_auto_20210517_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
