# Generated by Django 3.1.6 on 2021-06-09 10:17

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal", "0004_auto_20210521_1450"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndexPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", tinymce.models.HTMLField()),
            ],
            options={
                "verbose_name": "IndexPage",
                "verbose_name_plural": "IndexPage",
            },
        ),
    ]
