# Generated by Django 3.1.6 on 2021-11-18 15:25

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0008_auto_20210705_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprintPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'ImprintPage',
                'verbose_name_plural': 'ImprintPage',
            },
        ),
    ]
