# Generated by Django 3.2.12 on 2022-03-02 14:32

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0009_imprintpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TomsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'TomsPage',
                'verbose_name_plural': 'TomsPage',
            },
        ),
    ]
