# Generated by Django 2.2.8 on 2020-08-10 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_auto_20200810_1435"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="event_subject",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="ref_id",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="ref_text",
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="core.NotificationGroup",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="sub_type",
            field=models.CharField(
                choices=[
                    ("RECORD_MESSAGE", "RECORD_MESSAGE"),
                    ("RECORD_UPDATE", "RECORD_UPDATE"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="description_text",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="event",
            field=models.CharField(
                choices=[
                    ("CREATED", "CREATED"),
                    ("DELETED", "DELETED"),
                    ("MOVED", "MOVED"),
                    ("UPDATED", "UPDATED"),
                    ("ADDED", "ADDED"),
                    ("REMOVED", "REMOVED"),
                ],
                max_length=50,
            ),
        ),
    ]
