# Generated by Django 2.2.8 on 2020-08-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_auto_20200813_1324"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("RECORD__CREATED", "RECORD__CREATED"),
                    ("RECORD__UPDATED", "RECORD__UPDATED"),
                    ("RECORD__DELETED", "RECORD__DELETED"),
                    ("RECORD__RECORD_MESSAGE_ADDED", "RECORD__RECORD_MESSAGE_ADDED"),
                    ("RECORD__RECORD_DOCUMENT_ADDED", "RECORD__RECORD_DOCUMENT_ADDED"),
                    (
                        "RECORD__RECORD_DOCUMENT_MODIFIED",
                        "RECORD__RECORD_DOCUMENT_MODIFIED",
                    ),
                    ("RECORD__CLIENT_UPDATE", "RECORD__CLIENT_UPDATE"),
                    (
                        "RECORD_PERMISSION_REQUEST__REQUESTED",
                        "RECORD_PERMISSION_REQUEST__REQUESTED",
                    ),
                    (
                        "RECORD_PERMISSION_REQUEST__PROCESSED",
                        "RECORD_PERMISSION_REQUEST__PROCESSED",
                    ),
                    (
                        "RECORD_DELETION_REQUEST__REQUESTED",
                        "RECORD_DELETION_REQUEST__REQUESTED",
                    ),
                    (
                        "RECORD_DELETION_REQUEST__PROCESSED",
                        "RECORD_DELETION_REQUEST__PROCESSED",
                    ),
                    ("USER_REQUEST__REQUESTED", "USER_REQUEST__REQUESTED"),
                    ("USER_REQUEST__PROCESSED", "USER_REQUEST__PROCESSED"),
                    ("GROUP__ADDED_ME", "GROUP__ADDED_ME"),
                    ("GROUP__REMOVED_ME", "GROUP__REMOVED_ME"),
                ],
                default="",
                max_length=75,
            ),
        ),
    ]
