# Generated by Django 3.1.7 on 2021-03-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_auto_20201125_0956"),
        ("core", "0032_auto_20210201_1130"),
        ("core", "0032_auto_20210317_1048"),
    ]

    operations = []
