# Generated by Django 3.1.7 on 2021-03-26 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_remove_newuserrequest_after_password_forgotten"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuserrequest",
            name="request_processed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="new_user_requests_processed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
