# Generated by Django 3.1.6 on 2021-05-13 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_auto_20210512_1906"),
    ]

    operations = [
        migrations.AddField(
            model_name="rlcuser",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rlcuser",
            name="city",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="rlcuser",
            name="email_confirmed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="rlcuser",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rlcuser",
            name="phone_number",
            field=models.CharField(blank=True, default=None, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name="rlcuser",
            name="postal_code",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="rlcuser",
            name="rlc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="core.rlc",
            ),
        ),
        migrations.AddField(
            model_name="rlcuser",
            name="street",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="rlcuser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rlc_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
