# Generated by Django 3.1.6 on 2021-06-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_auto_20210513_1441"),
    ]

    operations = [
        migrations.AddField(
            model_name="rlc",
            name="use_record_pool",
            field=models.BooleanField(default=False),
        ),
    ]
