# Generated by Django 3.2.11 on 2022-02-12 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0087_auto_20220213_0006"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="note",
        ),
    ]
