# Generated by Django 3.2.13 on 2022-06-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0098_rlcuser_speciality_of_study"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersrlckeys",
            name="correct",
            field=models.BooleanField(default=True),
        ),
    ]
