# Generated by Django 3.2.14 on 2022-07-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_article_helppage_imprintpage_indexpage_internaluser_roadmapitem_tomspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rlc',
            name='private_key',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rlc',
            name='public_key',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
    ]
