# Generated by Django 3.2.14 on 2022-07-27 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_auto_20220727_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rlcuser',
            old_name='private_key_encrypted',
            new_name='is_private_key_encrypted',
        ),
    ]
