# Generated by Django 3.2.15 on 2022-08-11 20:55

import django.db.models.deletion
from django.db import migrations, models

import apps.core.seedwork.encryption


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0107_rename_userencryptionkeys_olduserencryptionkeys"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollabDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=4096)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "rlc",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collab_documents",
                        to="core.rlc",
                    ),
                ),
            ],
            options={
                "verbose_name": "CollabDocument",
                "verbose_name_plural": "CollabDocuments",
                "ordering": ["path"],
                "unique_together": {("rlc", "path")},
            },
        ),
        migrations.CreateModel(
            name="CollabPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "CollabPermission",
                "verbose_name_plural": "CollabPermissions",
            },
        ),
        migrations.CreateModel(
            name="TextDocumentVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.BinaryField(blank=True)),
                ("quill", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="core.collabdocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "TextDocumentVersion",
                "verbose_name_plural": "TextDocumentVersions",
            },
            bases=(apps.core.seedwork.encryption.EncryptedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PermissionForCollabDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collab_permissions",
                        to="core.collabdocument",
                    ),
                ),
                (
                    "group_has_permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_has_collab_permission",
                        to="core.group",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_permission_for_document",
                        to="core.collabpermission",
                    ),
                ),
            ],
            options={
                "unique_together": {("permission", "group_has_permission", "document")},
            },
        ),
    ]
