# Generated by Django 3.2.15 on 2022-08-12 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_collabdocument_collabpermission_permissionforcollabdocument_textdocumentversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_folders', to='core.folder')),
                ('rlc', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='core.rlc')),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
            },
        ),
        migrations.CreateModel(
            name='FolderPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'FolderPermission',
                'verbose_name_plural': 'FolderPermissions',
            },
        ),
        migrations.CreateModel(
            name='PermissionForFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_permissions_for_folder', to='core.folder')),
                ('group_has_permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_has_folder_permissions', to='core.group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_permission_for_folder', to='core.folderpermission')),
            ],
            options={
                'verbose_name': 'PermissionForFolder',
                'verbose_name_plural': 'PermissionsForFolders',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=1000, null=True, unique=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/file/')),
                ('exists', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files_created', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_in_folder', to='core.folder')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ['exists', '-created'],
            },
        ),
    ]
