# Generated by Django 3.2.15 on 2022-08-15 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0109_file_folder_folderpermission_permissionforfolder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationgroup",
            name="user",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.DeleteModel(
            name="NotificationGroup",
        ),
    ]
