# Generated by Django 3.2.15 on 2022-08-15 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0140_alter_recordstandardentry_value"),
        ("core", "0111_rename_usersrlckeys_orgencryption"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Rlc",
            new_name="Org",
        ),
    ]
