# Generated by Django 4.0.7 on 2022-09-23 10:40

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_alter_rlcuser_frontend_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('content', tinymce.models.HTMLField()),
                ('accept_required', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LegalRequirement',
                'verbose_name_plural': 'LegalRequirements',
            },
        ),
        migrations.CreateModel(
            name='LegalRequirementUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('legal_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_requirements_user', to='core.legalrequirement')),
                ('rlc_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_requirements_user', to='core.rlcuser')),
            ],
            options={
                'verbose_name': 'LegalRequirementUser',
                'verbose_name_plural': 'LegalRequirementUsers',
            },
        ),
        migrations.CreateModel(
            name='LegalRequirementEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('accepted', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rlcuser')),
                ('legal_requirement_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.legalrequirementuser')),
            ],
            options={
                'verbose_name': 'LegalRequirementEvent',
                'verbose_name_plural': 'LegalRequirementEvents',
            },
        ),
        migrations.AddField(
            model_name='legalrequirement',
            name='rlc_users',
            field=models.ManyToManyField(related_name='legal_requirements', through='core.LegalRequirementUser', to='core.rlcuser'),
        ),
    ]
