# Generated by Django 4.0.7 on 2022-09-26 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0115_legalrequirement_legalrequirementuser_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="rlc",
            new_name="rlc_old",
        ),
    ]
