# Generated by Django 4.0.7 on 2022-09-28 13:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_alter_rlcuser_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=1000)),
                ('order', models.IntegerField()),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='core.org')),
            ],
            options={
                'verbose_name': 'ExternalLink',
                'verbose_name_plural': 'ExternalLinks',
                'ordering': ['order'],
            },
        ),
    ]
