# Generated by Django 4.0.7 on 2022-10-02 18:31

import django.db.models.deletion
from django.db import migrations, models


def update_haspermissions(apps, schema_editor):
    HasPermission = apps.get_model("core", "HasPermission")

    for h in list(HasPermission.objects.select_related("user_has_permission").all()):
        if h.user_has_permission:
            h.user = h.user_has_permission.rlc_user
            h.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0119_externallink"),
    ]

    operations = [
        migrations.AddField(
            model_name="haspermission",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissions",
                to="core.rlcuser",
            ),
        ),
        migrations.RunPython(update_haspermissions),
    ]
