# Generated by Django 4.0.7 on 2022-10-03 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0120_haspermission_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="haspermission",
            unique_together={("permission", "user", "group_has_permission")},
        ),
        migrations.RemoveField(
            model_name="haspermission",
            name="user_has_permission",
        ),
    ]
