# Generated by Django 3.2.15 on 2022-10-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0119_event"),
        ("core", "0121_alter_haspermission_unique_together_and_more"),
    ]

    operations = []
