# Generated by Django 4.0.7 on 2022-10-05 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_group_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_members',
        ),
    ]
