# Generated by Django 4.0.7 on 2022-10-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0124_encryptedclient_origincountry_questionnaire_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="encryptedclient",
            name="birthday",
        ),
        migrations.RemoveField(
            model_name="encryptedclient",
            name="origin_country",
        ),
        migrations.DeleteModel(
            name="OriginCountry",
        ),
    ]
