# Generated by Django 4.0.7 on 2022-10-12 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_delete_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryptedrecorddocument',
            name='creator',
        ),
    ]
