# Generated by Django 4.0.7 on 2022-10-12 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_encryptedrecordmessage_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryptedrecordmessage',
            name='sender_old',
        ),
    ]
