# Generated by Django 4.0.7 on 2022-10-12 10:01

from django.db import migrations, models


def move_value(apps, schema_editor):
    RecordUsersEntry = apps.get_model("core", "RecordUsersEntry")

    for m in list(RecordUsersEntry.objects.all()):
        for u in list(m.value_old.all()):
            m.value.add(u.rlc_user)
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_rename_value_recordusersentry_value_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordusersentry',
            name='value',
            field=models.ManyToManyField(blank=True, to='core.rlcuser'),
        ),
        migrations.RunPython(move_value)
    ]
