# Generated by Django 4.0.7 on 2022-10-12 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_recordusersentry_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordusersentry',
            name='value_old',
        ),
    ]
