# Generated by Django 4.0.7 on 2022-10-12 10:34

from django.db import migrations, models
import django.db.models.deletion


def move_value(apps, schema_editor):
    RecordUsersEntry = apps.get_model("core", "RecordUsersEntry")

    for m in list(RecordUsersEntry.objects.all()):
        for u in list(m.value_old.all()):
            m.value.add(u.rlc_user)
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_rename_user_recordencryptionnew_user_old_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordencryptionnew',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordencryptions', to='core.rlcuser'),
        ),
        migrations.RunPython(migrate_encryptions)
    ]
