# Generated by Django 4.0.7 on 2022-10-12 10:34

import django.db.models.deletion
from django.db import migrations, models


def migrate_encryptions(apps, schema_editor):
    RecordEncryptionsNew = apps.get_model("core", "RecordEncryptionNew")

    for e in list(RecordEncryptionsNew.objects.all()):
        e.user = e.user_old.rlc_user
        e.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0135_rename_user_recordencryptionnew_user_old_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordencryptionnew",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recordencryptions",
                to="core.rlcuser",
            ),
        ),
        migrations.RunPython(migrate_encryptions),
    ]
