# Generated by Django 4.0.7 on 2022-10-12 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0136_recordencryptionnew_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="recordencryptionnew",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="recordencryptionnew",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recordencryptions",
                to="core.rlcuser",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recordencryptionnew",
            unique_together={("user", "record")},
        ),
        migrations.RemoveField(
            model_name="recordencryptionnew",
            name="user_old",
        ),
    ]
