# Generated by Django 4.0.7 on 2022-10-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_alter_event_options'),
        ('core', '0138_alter_encryptedrecordmessage_record'),
    ]

    operations = [
    ]
