# Generated by Django 2.2.2 on 2019-12-03 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0007_auto_20191203_1210"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recorddeletionrequest",
            name="request_from",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
