# Generated by Django 2.2.8 on 2020-01-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0010_auto_20200106_2320"),
    ]

    operations = [
        migrations.AddField(
            model_name="encryptedclient",
            name="encrypted_client_key",
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name="encryptedclient",
            name="name",
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name="encryptedclient",
            name="note",
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name="encryptedclient",
            name="phone_number",
            field=models.BinaryField(null=True),
        ),
    ]
