# Generated by Django 2.2.8 on 2020-01-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0011_auto_20200108_1640"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClientEncryption",
        ),
    ]
