# Generated by Django 2.2.8 on 2020-01-17 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0012_delete_clientencryption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryptedrecorddocument",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
