# Generated by Django 2.2.8 on 2020-08-14 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0017_auto_20200814_1031"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryptedrecorddeletionrequest",
            name="requested",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
