# Generated by Django 3.1.6 on 2021-06-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0034_auto_20210603_1619"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EncryptedRecordDocumentDeletionRequest",
        ),
    ]
