# Generated by Django 3.1.6 on 2021-06-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0036_encryptedrecorddocument_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="encryptedrecorddocument",
            name="exists",
            field=models.BooleanField(default=True),
        ),
    ]
