# Generated by Django 3.1.6 on 2021-06-22 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recordmanagement", "0037_encryptedrecorddocument_exists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryptedrecordpermission",
            name="processed_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="encryptedrecordpermission",
            name="request_processed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="e_record_permissions_processed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
