# Generated by Django 3.1.6 on 2021-09-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0039_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="encryptedrecord",
            name="tags",
            field=models.ManyToManyField(
                related_name="records", to="recordmanagement.Tag"
            ),
        ),
    ]
