# Generated by Django 3.1.6 on 2021-09-24 09:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0040_encryptedrecord_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
