# Generated by Django 3.1.6 on 2021-09-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0041_auto_20210924_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedrecord',
            name='tagged',
            field=models.ManyToManyField(blank=True, related_name='e_tagged', to='recordmanagement.RecordTag'),
        ),
    ]
