# Generated by Django 3.1.6 on 2021-10-11 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recordmanagement", "0043_auto_20210924_1811"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryptedrecorddeletionrequest",
            name="processed_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="encryptedrecorddeletionrequest",
            name="record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deletions_requested",
                to="recordmanagement.encryptedrecord",
            ),
        ),
        migrations.AlterField(
            model_name="encryptedrecorddeletionrequest",
            name="request_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="encryptedrecorddeletionrequest",
            name="request_processed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="e_record_deletion_request_processed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
