# Generated by Django 3.1.6 on 2021-10-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0044_auto_20211011_2103"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryptedrecorddeletionrequest",
            name="explanation",
            field=models.TextField(blank=True, default=""),
        ),
    ]
