# Generated by Django 3.1.6 on 2021-10-11 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0045_auto_20211011_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryptedrecord',
            name='tagged',
        ),
        migrations.DeleteModel(
            name='RecordTag',
        ),
    ]
