# Generated by Django 3.1.6 on 2021-10-11 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0046_auto_20211011_2145"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="encryptedrecorddocument",
            name="tagged",
        ),
        migrations.DeleteModel(
            name="RecordDocumentTag",
        ),
    ]
