# Generated by Django 3.1.6 on 2021-10-14 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_auto_20211011_2158'),
        ('recordmanagement', '0047_auto_20211011_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('questionnaire', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Questionnaire',
                'verbose_name_plural': 'Questionnaire',
            },
        ),
        migrations.CreateModel(
            name='RecordQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record_questionnaires', to='recordmanagement.questionnaire')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='recordmanagement.encryptedrecord')),
            ],
            options={
                'verbose_name': 'RecordQuestionnaire',
                'verbose_name_plural': 'RecordQuestionnaires',
            },
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='records',
            field=models.ManyToManyField(through='recordmanagement.RecordQuestionnaire', to='recordmanagement.EncryptedRecord'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='rlc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='api.rlc'),
        ),
    ]
