# Generated by Django 3.1.6 on 2021-10-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0048_auto_20211014_1648"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordquestionnaire",
            name="answered",
            field=models.BooleanField(default=False),
        ),
    ]
