# Generated by Django 3.1.6 on 2021-10-16 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_remove_userprofile_is_active'),
        ('recordmanagement', '0050_questionnaire_allow_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='rlc',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='api.rlc'),
        ),
    ]
