# Generated by Django 3.1.6 on 2021-10-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0051_auto_20211016_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordquestionnaire',
            name='code',
            field=models.SlugField(default='12321KD', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recordquestionnaire',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
