# Generated by Django 3.1.6 on 2021-11-22 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0054_encryptedrecorddeletionrequest_rlc"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionnaireField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=100)),
                ("type", models.CharField(choices=[("FILE", "File")], max_length=20)),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="recordmanagement.questionnaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "QuestionnaireField",
                "verbose_name_plural": "QuestionnaireFields",
            },
        ),
    ]
