# Generated by Django 3.1.6 on 2021-11-22 12:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0055_questionnairefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairefield',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnairefield',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='QuestionnaireAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FILE', 'File')], max_length=20)),
                ('data', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('record_questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='recordmanagement.recordquestionnaire')),
            ],
            options={
                'verbose_name': 'QuestionnaireAnswer',
                'verbose_name_plural': 'QuestionnaireAnswers',
            },
        ),
    ]
