# Generated by Django 3.1.6 on 2021-11-22 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0056_auto_20211122_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaireanswer',
            name='type',
        ),
        migrations.AddField(
            model_name='questionnaireanswer',
            name='field',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='recordmanagement.questionnairefield'),
            preserve_default=False,
        ),
    ]
