# Generated by Django 3.1.6 on 2021-11-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0057_auto_20211122_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireanswer',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
