# Generated by Django 3.1.6 on 2021-11-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0058_auto_20211122_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordquestionnaire',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='recordquestionnaire',
            name='answered',
        ),
    ]
