# Generated by Django 3.1.6 on 2021-11-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0059_auto_20211122_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='allow_file_upload',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='questionnaire',
        ),
        migrations.AlterField(
            model_name='questionnairefield',
            name='type',
            field=models.CharField(choices=[('FILE', 'File'), ('TEXTAREA', 'Text')], max_length=20),
        ),
    ]
