# Generated by Django 3.2.9 on 2021-11-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0062_auto_20211124_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireanswer',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
