# Generated by Django 3.2.9 on 2021-11-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0063_alter_questionnaireanswer_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireanswer',
            name='data',
            field=models.BinaryField(default=None),
            preserve_default=False,
        ),
    ]
