# Generated by Django 3.2.9 on 2021-11-28 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0066_alter_questionnaireanswer_aes_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='questionnairefile/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='recordmanagement.questionnaire')),
            ],
            options={
                'verbose_name': 'QuestionnaireFile',
                'verbose_name_plural': 'QuestionnaireFiles',
            },
        ),
    ]
