# Generated by Django 3.2.9 on 2021-12-16 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.records.models.record
import apps.static.encryption


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_alter_rlcuser_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recordmanagement", "0067_questionnairefile"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "rlc",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordtemplates",
                        to="core.rlc",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordTemplate",
                "verbose_name_plural": "RecordTemplates",
            },
        ),
        migrations.AlterField(
            model_name="tag",
            name="rlc",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="core.rlc",
            ),
        ),
        migrations.CreateModel(
            name="RecordUsersField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("order", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users_fields",
                        to="recordmanagement.recordtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordUsersField",
                "verbose_name_plural": "RecordUsersFields",
            },
        ),
        migrations.CreateModel(
            name="RecordStateField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("order", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("states", models.JSONField()),
                (
                    "template",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_fields",
                        to="recordmanagement.recordtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordStateField",
                "verbose_name_plural": "RecordStateFields",
            },
        ),
        migrations.CreateModel(
            name="RecordStandardField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("order", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("TEXTAREA", "Multi Line"),
                            ("TEXT", "Single Line"),
                            ("DATETIME-LOCAL", "Date and Time"),
                            ("DATE", "Date"),
                        ],
                        default="TEXT",
                        max_length=20,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_fields",
                        to="recordmanagement.recordtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordStandardField",
                "verbose_name_plural": "RecordStandardFields",
            },
        ),
        migrations.CreateModel(
            name="RecordSelectField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("order", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("options", models.JSONField()),
                ("multiple", models.BooleanField(default=False)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multiple_fields",
                        to="recordmanagement.recordtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordSelectField",
                "verbose_name_plural": "RecordSelectFields",
            },
        ),
        migrations.CreateModel(
            name="RecordEncryptedStandardField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("order", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("TEXTAREA", "Multi Line"),
                            ("TEXT", "Single Line"),
                            ("DATE", "Date"),
                        ],
                        default="TEXT",
                        max_length=20,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_fields",
                        to="recordmanagement.recordtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordEncryptedStandardField",
                "verbose_name_plural": "RecordEncryptedStandardFields",
            },
        ),
        migrations.CreateModel(
            name="RecordEncryptedSelectField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("order", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("multiple", models.BooleanField(default=False)),
                ("options", models.JSONField()),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="select_fields",
                        to="recordmanagement.recordtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordEncryptedSelectField",
                "verbose_name_plural": "RecordEncryptedSelectFields",
            },
        ),
        migrations.CreateModel(
            name="RecordEncryptedFileField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("order", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_fields",
                        to="recordmanagement.recordtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordEncryptedFileField",
                "verbose_name_plural": "RecordEncryptedFileFields",
            },
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "old_record",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="record",
                        to="recordmanagement.encryptedrecord",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="recordmanagement.recordtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Record",
                "verbose_name_plural": "Records",
            },
        ),
        migrations.CreateModel(
            name="RecordUsersEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="recordmanagement.recordusersfield",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users_entries",
                        to="recordmanagement.record",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "RecordUsersEntry",
                "verbose_name_plural": "RecordUsersEntries",
                "unique_together": {("record", "field")},
            },
        ),
        migrations.CreateModel(
            name="RecordStateEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("state", models.CharField(max_length=1000)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="recordmanagement.recordstatefield",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_entries",
                        to="recordmanagement.record",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordStateEntry",
                "verbose_name_plural": "RecordStateEntries",
                "unique_together": {("record", "field")},
            },
        ),
        migrations.CreateModel(
            name="RecordStandardEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("text", models.CharField(max_length=500)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="recordmanagement.recordstandardfield",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_entries",
                        to="recordmanagement.record",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordStandardEntry",
                "verbose_name_plural": "RecordStandardEntries",
                "unique_together": {("record", "field")},
            },
        ),
        migrations.CreateModel(
            name="RecordSelectEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("value", models.JSONField()),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="recordmanagement.recordselectfield",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multiple_entries",
                        to="recordmanagement.record",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordSelectEntry",
                "verbose_name_plural": "RecordSelectEntries",
                "unique_together": {("record", "field")},
            },
        ),
        migrations.CreateModel(
            name="RecordEncryptionNew",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.BinaryField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encryptions",
                        to="recordmanagement.record",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordencryptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordEncryption",
                "verbose_name_plural": "RecordEncryptions",
                "unique_together": {("user", "record")},
            },
            bases=(apps.static.encryption.EncryptedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="RecordEncryptedStandardEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("text", models.BinaryField()),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="recordmanagement.recordencryptedstandardfield",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_entries",
                        to="recordmanagement.record",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordStandardEntry",
                "verbose_name_plural": "RecordStandardEntries",
                "unique_together": {("record", "field")},
            },
            bases=(
                apps.core.records.models.record.RecordEntryEncryptedModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="RecordEncryptedSelectEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("value", models.BinaryField()),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="recordmanagement.recordencryptedselectfield",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="select_entries",
                        to="recordmanagement.record",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordEncryptedSelectEntry",
                "verbose_name_plural": "RecordEncryptedSelectEntries",
                "unique_together": {("record", "field")},
            },
            bases=(
                apps.core.records.models.record.RecordEntryEncryptedModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="RecordEncryptedFileEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="recordfileentry/")),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="recordmanagement.recordencryptedfilefield",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_entries",
                        to="recordmanagement.record",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordEncryptedFileEntry",
                "verbose_name_plural": "RecordEncryptedFileEntries",
                "unique_together": {("record", "field")},
            },
        ),
    ]
