# Generated by Django 3.2.9 on 2021-12-05 18:12

import apps.static.encryption
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_remove_userprofile_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recordmanagement', '0067_questionnairefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
            },
        ),
        migrations.CreateModel(
            name='RecordFileField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'RecordFileField',
                'verbose_name_plural': 'RecordFileFields',
            },
        ),
        migrations.CreateModel(
            name='RecordTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rlc', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordtemplates', to='api.rlc')),
            ],
            options={
                'verbose_name': 'RecordTemplate',
                'verbose_name_plural': 'RecordTemplates',
            },
        ),
        migrations.CreateModel(
            name='RecordTextField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_fields', to='recordmanagement.recordtemplate')),
            ],
            options={
                'verbose_name': 'RecordTextField',
                'verbose_name_plural': 'RecordTextFields',
            },
        ),
        migrations.CreateModel(
            name='RecordTextFieldEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.BinaryField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='recordmanagement.recordtextfield')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_entries', to='recordmanagement.record')),
            ],
            options={
                'verbose_name': 'RecordTextFieldEntry',
                'verbose_name_plural': 'RecordTextFieldEntries',
            },
            bases=(apps.static.encryption.EncryptedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RecordFileFieldEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='recordfilefield/')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='recordmanagement.recordfilefield')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_entries', to='recordmanagement.record')),
            ],
            options={
                'verbose_name': 'RecordFileFieldEntry',
                'verbose_name_plural': 'RecordFileFieldEntries',
            },
        ),
        migrations.AddField(
            model_name='recordfilefield',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_fields', to='recordmanagement.recordtemplate'),
        ),
        migrations.AddField(
            model_name='record',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='recordmanagement.recordtemplate'),
        ),
        migrations.CreateModel(
            name='RecordEncryptionNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.BinaryField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encryptions', to='recordmanagement.record')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordencryptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RecordEncryption',
                'verbose_name_plural': 'RecordEncryptions',
                'unique_together': {('user', 'record')},
            },
            bases=(apps.static.encryption.EncryptedModelMixin, models.Model),
        ),
    ]
