# Generated by Django 3.2.9 on 2021-12-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0068_auto_20211205_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordtextfield',
            name='field_type',
            field=models.CharField(choices=[('TEXTAREA', 'Multi Line'), ('TEXT', 'Single Line')], default='TEXT', max_length=20),
            preserve_default=False,
        ),
    ]
