# Generated by Django 3.2.9 on 2021-12-17 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0068_auto_20211216_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordencryptedfilefield',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encrypted_file_fields', to='recordmanagement.recordtemplate'),
        ),
        migrations.AlterField(
            model_name='recordencryptedselectfield',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encrypted_select_fields', to='recordmanagement.recordtemplate'),
        ),
        migrations.AlterField(
            model_name='recordencryptedstandardfield',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encrypted_standard_fields', to='recordmanagement.recordtemplate'),
        ),
        migrations.AlterField(
            model_name='recordselectfield',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='select_fields', to='recordmanagement.recordtemplate'),
        ),
        migrations.AlterField(
            model_name='recordstandardfield',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_fields', to='recordmanagement.recordtemplate'),
        ),
    ]
