# Generated by Django 3.2.9 on 2021-12-17 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0069_auto_20211217_1742"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordencryptedfileentry",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="encrypted_file_entries",
                to="recordmanagement.record",
            ),
        ),
        migrations.AlterField(
            model_name="recordencryptedselectentry",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="encrypted_select_entries",
                to="recordmanagement.record",
            ),
        ),
        migrations.AlterField(
            model_name="recordencryptedstandardentry",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="encrypted_standard_entries",
                to="recordmanagement.record",
            ),
        ),
        migrations.AlterField(
            model_name="recordselectentry",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="select_entries",
                to="recordmanagement.record",
            ),
        ),
        migrations.AlterField(
            model_name="recordstandardentry",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="standard_entries",
                to="recordmanagement.record",
            ),
        ),
    ]
