# Generated by Django 3.2.9 on 2021-12-05 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0069_recordtextfield_field_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecordFileFieldEntry',
            new_name='RecordFileEntry',
        ),
        migrations.RenameModel(
            old_name='RecordTextFieldEntry',
            new_name='RecordTextEntry',
        ),
    ]
