# Generated by Django 3.2.9 on 2021-12-05 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0070_auto_20211205_2029'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recordtextentry',
            unique_together={('record', 'field')},
        ),
    ]
