# Generated by Django 3.2.9 on 2021-12-18 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0071_record_old_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='old_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='recordmanagement.encryptedclient'),
        ),
    ]
