# Generated by Django 3.2.9 on 2021-12-06 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0071_alter_recordtextentry_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordMetaField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_fields', to='recordmanagement.recordtemplate')),
            ],
            options={
                'verbose_name': 'RecordMetaField',
                'verbose_name_plural': 'RecordMetaFields',
            },
        ),
        migrations.CreateModel(
            name='RecordMetaEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='recordmanagement.recordmetafield')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_entries', to='recordmanagement.record')),
            ],
            options={
                'verbose_name': 'RecordMetaEntry',
                'verbose_name_plural': 'RecordMetaEntries',
                'unique_together': {('record', 'field')},
            },
        ),
    ]
