# Generated by Django 3.2.9 on 2021-12-09 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0072_recordmetaentry_recordmetafield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordfileentry',
            options={'verbose_name': 'RecordFileEntry', 'verbose_name_plural': 'RecordFileEntries'},
        ),
        migrations.AlterField(
            model_name='recordfileentry',
            name='file',
            field=models.FileField(upload_to='recordfileentry/'),
        ),
        migrations.AlterUniqueTogether(
            name='recordfileentry',
            unique_together={('record', 'field')},
        ),
        migrations.CreateModel(
            name='RecordSelectField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('options', models.JSONField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='select_fields', to='recordmanagement.recordtemplate')),
            ],
            options={
                'verbose_name': 'RecordSelectField',
                'verbose_name_plural': 'RecordSelectFields',
            },
        ),
        migrations.CreateModel(
            name='RecordSelectEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='recordmanagement.recordselectfield')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='select_entries', to='recordmanagement.record')),
            ],
            options={
                'verbose_name': 'RecordSelectEntry',
                'verbose_name_plural': 'RecordSelectEntries',
                'unique_together': {('record', 'field')},
            },
        ),
    ]
