# Generated by Django 3.2.9 on 2021-12-18 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0072_alter_record_old_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordstatefield",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="state_fields",
                to="recordmanagement.recordtemplate",
            ),
        ),
    ]
