# Generated by Django 3.2.9 on 2021-12-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0073_auto_20211209_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordselectfield',
            name='multiple',
            field=models.BooleanField(default=False),
        ),
    ]
