# Generated by Django 3.2.9 on 2021-12-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0074_recordselectfield_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordselectentry',
            name='value',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
    ]
