# Generated by Django 3.2.9 on 2021-12-14 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_remove_userprofile_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recordmanagement', '0075_recordselectentry_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordfilefield',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recordmetafield',
            name='field_type',
            field=models.CharField(choices=[('TEXTAREA', 'Multi Line'), ('TEXT', 'Single Line'), ('DATETIME-LOCAL', 'Date and Time'), ('DATE', 'Date')], default='TEXT', max_length=20),
        ),
        migrations.AddField(
            model_name='recordmetafield',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recordselectfield',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recordtextfield',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recordtextfield',
            name='field_type',
            field=models.CharField(choices=[('TEXTAREA', 'Multi Line'), ('TEXT', 'Single Line'), ('DATE', 'Date')], default='TEXT', max_length=20),
        ),
        migrations.AlterField(
            model_name='tag',
            name='rlc',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='api.rlc'),
        ),
        migrations.CreateModel(
            name='RecordUsersField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_fields', to='recordmanagement.recordtemplate')),
            ],
            options={
                'verbose_name': 'RecordUsersField',
                'verbose_name_plural': 'RecordUsersFields',
            },
        ),
        migrations.CreateModel(
            name='RecordUsersEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='recordmanagement.recordusersfield')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_entries', to='recordmanagement.record')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RecordUsersEntry',
                'verbose_name_plural': 'RecordUsersEntries',
                'unique_together': {('record', 'field')},
            },
        ),
    ]
