# Generated by Django 3.2.9 on 2021-12-23 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0075_rename_text_recordencryptedstandardentry_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recordstandardentry',
            old_name='text',
            new_name='value',
        ),
    ]
