# Generated by Django 3.2.9 on 2021-12-14 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recordmanagement', '0076_auto_20211214_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordusersentry',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
