# Generated by Django 3.2.9 on 2021-12-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0076_rename_text_recordstandardentry_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recordstateentry',
            old_name='state',
            new_name='value',
        ),
    ]
