# Generated by Django 3.2.9 on 2021-12-16 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0077_alter_recordusersentry_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordStateField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('states', models.JSONField()),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state_fields', to='recordmanagement.recordtemplate')),
            ],
            options={
                'verbose_name': 'RecordStateField',
                'verbose_name_plural': 'RecordStateFields',
            },
        ),
        migrations.CreateModel(
            name='RecordStateEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=1000)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='recordmanagement.recordstatefield')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_entries', to='recordmanagement.record')),
            ],
            options={
                'verbose_name': 'RecordStateEntry',
                'verbose_name_plural': 'RecordStateEntries',
                'unique_together': {('record', 'field')},
            },
        ),
    ]
