# Generated by Django 3.2.9 on 2021-12-23 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0077_rename_state_recordstateentry_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recordusersentry',
            old_name='users',
            new_name='value',
        ),
    ]
