# Generated by Django 3.2.9 on 2021-12-16 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0078_recordstateentry_recordstatefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='old_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record', to='recordmanagement.encryptedrecord'),
        ),
    ]
