# Generated by Django 3.2.9 on 2021-12-23 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0079_auto_20211223_1258"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recordselectfield",
            name="multiple",
        ),
        migrations.CreateModel(
            name="RecordMultipleField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("order", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("options", models.JSONField()),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multiple_fields",
                        to="recordmanagement.recordtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordMultipleField",
                "verbose_name_plural": "RecordMultipleFields",
            },
        ),
        migrations.CreateModel(
            name="RecordMultipleEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("value", models.JSONField()),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="recordmanagement.recordmultiplefield",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multiple_entries",
                        to="recordmanagement.record",
                    ),
                ),
            ],
            options={
                "verbose_name": "RecordMultipleEntry",
                "verbose_name_plural": "RecordMultipleEntries",
                "unique_together": {("record", "field")},
            },
        ),
        migrations.AlterField(
            model_name="encryptedrecorddocument",
            name="record",
            field=models.ForeignKey(
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="recordmanagement.record",
            ),
        ),
    ]
