# Generated by Django 3.2.9 on 2021-12-23 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0080_auto_20211223_1302"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recordstatefield",
            old_name="states",
            new_name="options",
        ),
    ]
