# Generated by Django 3.2.9 on 2021-12-23 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0081_rename_states_recordstatefield_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="encryptedrecordmessage",
            old_name="record",
            new_name="old_record",
        ),
    ]
