# Generated by Django 3.2.9 on 2021-12-23 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recordmanagement", "0083_auto_20211223_1901"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryptedrecordmessage",
            name="old_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="recordmanagement.encryptedrecord",
            ),
        ),
        migrations.AlterField(
            model_name="encryptedrecordmessage",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="e_record_messages_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
