# Generated by Django 3.2.9 on 2021-12-25 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0084_auto_20211223_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encryptedrecorddocument',
            old_name='record',
            new_name='old_record',
        ),
    ]
