# Generated by Django 3.2.9 on 2021-12-25 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0085_rename_record_encryptedrecorddocument_old_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="encryptedrecorddocument",
            name="record",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="recordmanagement.record",
            ),
        ),
    ]
