# Generated by Django 3.2.9 on 2021-12-25 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0085_rename_record_encryptedrecorddocument_old_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedrecorddocument',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='recordmanagement.record'),
        ),
    ]
