# Generated by Django 3.2.9 on 2021-12-25 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0087_alter_encryptedrecorddocument_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedrecorddocument',
            name='old_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_record_documents', to='recordmanagement.encryptedrecord'),
        ),
    ]
