# Generated by Django 3.2.9 on 2021-12-25 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0089_rename_questionnaire_questionnairetemplate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionnaireFile',
            new_name='QuestionnaireTemplateFile',
        ),
    ]
