# Generated by Django 3.2.9 on 2021-12-25 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0092_rename_questionnairefield_questionnairequestion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questionnaire",
            old_name="record",
            new_name="old_record",
        ),
    ]
