# Generated by Django 3.2.9 on 2021-12-25 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0093_rename_record_questionnaire_old_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questionnaires",
                to="recordmanagement.record",
            ),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="old_record",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questionnaires",
                to="recordmanagement.encryptedrecord",
            ),
        ),
    ]
