# Generated by Django 3.2.9 on 2021-12-25 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0094_auto_20211225_1412"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionnaire",
            name="questionnaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="questionnaires",
                to="recordmanagement.questionnairetemplate",
            ),
        ),
    ]
