# Generated by Django 3.2.9 on 2021-12-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recordmanagement",
            "0097_rename_record_questionnaire_questionnaireanswer_questionnaire",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordstandardentry",
            name="value",
            field=models.CharField(max_length=1000),
        ),
    ]
