# Generated by Django 3.2.9 on 2021-12-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0098_alter_recordstandardentry_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordstandardentry',
            name='value',
            field=models.TextField(max_length=1000),
        ),
    ]
