# Generated by Django 3.2.9 on 2021-12-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0099_alter_recordstandardentry_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordencryptedselectfield',
            name='options',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='recordmultiplefield',
            name='options',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='recordselectfield',
            name='options',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='recordstatefield',
            name='options',
            field=models.JSONField(default=list),
        ),
    ]
