# Generated by Django 3.2.10 on 2022-01-03 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0100_auto_20211228_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedrecorddeletionrequest',
            name='record',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletions_requested', to='recordmanagement.encryptedrecord'),
        ),
    ]
