# Generated by Django 3.2.10 on 2022-01-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0101_alter_encryptedrecorddeletionrequest_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encryptedrecorddeletionrequest',
            old_name='record',
            new_name='old_record',
        ),
    ]
