# Generated by Django 3.2.10 on 2022-01-03 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0102_rename_record_encryptedrecorddeletionrequest_old_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedrecorddeletionrequest',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletions', to='recordmanagement.record'),
        ),
    ]
