# Generated by Django 3.2.10 on 2022-01-03 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0076_alter_rlcuser_options"),
        ("recordmanagement", "0105_encryptedrecorddeletionrequest_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryptedrecorddeletionrequest",
            name="old_record",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="recordmanagement.encryptedrecord",
            ),
        ),
        migrations.AlterField(
            model_name="encryptedrecorddeletionrequest",
            name="request_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requestedrecorddeletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="encryptedrecorddeletionrequest",
            name="request_processed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processedrecorddeletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
