# Generated by Django 3.2.10 on 2022-01-03 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0106_auto_20220103_1836"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="encryptedrecorddeletionrequest",
            name="rlc",
        ),
    ]
