# Generated by Django 3.2.10 on 2022-01-03 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recordmanagement', '0107_remove_encryptedrecorddeletionrequest_rlc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedrecorddeletionrequest',
            name='request_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestedrecorddeletions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='encryptedrecorddeletionrequest',
            name='request_processed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processedrecorddeletions', to=settings.AUTH_USER_MODEL),
        ),
    ]
