# Generated by Django 3.2.10 on 2022-01-03 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0109_auto_20220103_1903"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="encryptedrecorddeletionrequest",
            name="old_record",
        ),
    ]
