# Generated by Django 3.2.10 on 2022-01-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0113_rename_request_from_recorddeletion_requested_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recorddeletion",
            name="explanation",
            field=models.TextField(),
        ),
    ]
