# Generated by Django 3.2.10 on 2022-01-03 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0114_alter_recorddeletion_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorddeletion',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletions', to='recordmanagement.record'),
        ),
    ]
