# Generated by Django 3.2.10 on 2022-01-03 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0117_rename_requested_from_recorddeletion_requested_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recorddeletion",
            old_name="processed_on",
            new_name="processed",
        ),
    ]
