# Generated by Django 3.2.10 on 2022-01-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0120_auto_20220105_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encryptedrecordpermission',
            old_name='request_from',
            new_name='requested_by',
        ),
    ]
