# Generated by Django 3.2.10 on 2022-01-05 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "recordmanagement",
            "0121_rename_request_from_encryptedrecordpermission_requested_by",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryptedrecordpermission",
            name="processed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="processedrecordaccesses",
                to="api.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="encryptedrecordpermission",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requestedrecordaccesses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
