# Generated by Django 3.2.10 on 2022-01-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0122_auto_20220105_1623"),
    ]

    operations = [
        migrations.AddField(
            model_name="encryptedrecordpermission",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
