# Generated by Django 3.2.10 on 2022-01-05 15:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recordmanagement", "0123_encryptedrecordpermission_updated"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EncryptedRecordPermission",
            new_name="RecordAccess",
        ),
    ]
