# Generated by Django 3.2.10 on 2022-01-05 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0124_rename_encryptedrecordpermission_recordaccess"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordaccess",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="e_permissions_requested",
                to="recordmanagement.record",
            ),
        ),
    ]
