# Generated by Django 3.2.10 on 2022-01-05 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recordmanagement", "0125_alter_recordaccess_record"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recordaccess",
            options={
                "ordering": ["-state", "-created"],
                "verbose_name": "RecordAccess",
                "verbose_name_plural": "RecordAccesses",
            },
        ),
        migrations.AlterField(
            model_name="recordaccess",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="processedrecordaccesses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
