# Generated by Django 3.2.10 on 2022-01-09 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0129_auto_20220107_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recorddeletion',
            options={'ordering': ['-state', '-created'], 'verbose_name': 'RecordDeletion', 'verbose_name_plural': 'RecordDeletions'},
        ),
    ]
