# Generated by Django 3.2.10 on 2022-01-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0130_alter_recorddeletion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordencryptedfileentry',
            name='file',
            field=models.FileField(upload_to='recordmanagement/recordencryptedfileentry/'),
        ),
    ]
