# Generated by Django 3.2.12 on 2022-03-02 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_alter_note_rlc'),
        ('recordmanagement', '0131_alter_recordencryptedfileentry_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordusersfield',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.group'),
        ),
        migrations.AddField(
            model_name='recordusersfield',
            name='share_keys',
            field=models.BooleanField(default=True),
        ),
    ]
