# Generated by Django 3.2.12 on 2022-03-27 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recordmanagement", "0133_alter_record_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recorddeletion",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requestedrecorddeletions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
