# Generated by Django 3.2.12 on 2022-04-22 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0134_alter_recorddeletion_requested_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordStatisticField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('options', models.JSONField(default=list)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic_fields', to='recordmanagement.recordtemplate')),
            ],
            options={
                'verbose_name': 'RecordStatisticField',
                'verbose_name_plural': 'RecordStatisticFields',
            },
        ),
        migrations.CreateModel(
            name='RecordStatisticEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=200)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='recordmanagement.recordstatisticfield')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic_entries', to='recordmanagement.record')),
            ],
            options={
                'verbose_name': 'RecordStatisticEntry',
                'verbose_name_plural': 'RecordStatisticEntries',
                'unique_together': {('record', 'field')},
            },
        ),
    ]
