# Generated by Django 3.2.12 on 2022-04-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0135_recordstatisticentry_recordstatisticfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordstatisticfield",
            name="helptext",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
    ]
