# Generated by Django 3.2.13 on 2022-06-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0137_recordencryptionnew_correct"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordaccess",
            name="explanation",
            field=models.TextField(blank=True),
        ),
    ]
