# Generated by Django 3.2.14 on 2022-08-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0139_recordstateentry_closed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordstandardentry",
            name="value",
            field=models.TextField(max_length=20000),
        ),
    ]
