# Generated by Django 4.0.7 on 2022-09-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0140_alter_recordstandardentry_value"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="recordencryption",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="recordencryption",
            name="record",
        ),
        migrations.RemoveField(
            model_name="recordencryption",
            name="user",
        ),
        migrations.RemoveField(
            model_name="encryptedrecorddocument",
            name="old_record",
        ),
        migrations.RemoveField(
            model_name="encryptedrecordmessage",
            name="old_record",
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="old_record",
        ),
        migrations.RemoveField(
            model_name="record",
            name="old_record",
        ),
        migrations.AlterField(
            model_name="questionnairetemplate",
            name="records",
            field=models.ManyToManyField(
                through="recordmanagement.Questionnaire", to="recordmanagement.record"
            ),
        ),
        migrations.DeleteModel(
            name="EncryptedRecord",
        ),
        migrations.DeleteModel(
            name="RecordEncryption",
        ),
    ]
