from .auth.admin import *
from .collab.admin import *
from .data_sheets.admin import *
from .events.admin import *
from .files.admin import *
from .files_new.admin import *
from .folders.admin import *
from .internal.admin import *
from .legal.admin import *
from .mail.admin import *
from .mail_imports.admin import *
from .other.admin import *
from .permissions.admin import *
from .questionnaires.admin import *
from .records.admin import *
from .rlc.admin import *
from .statistics.admin import *
from .todos.admin import *
from .upload.admin import *
