# Generated by Django 3.0 on 2020-11-25 11:03

import backend.collab.models.editing_room
import backend.static.encryption
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0032_auto_20201125_0956"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("content", models.BinaryField()),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_edited",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="text_documents_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_editor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="text_documents_last_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rlc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_documents",
                        to="api.Rlc",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EditingRoom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        auto_created=True,
                        default=backend.static.encryption.AESEncryption.generate_secure_key,
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "room_id",
                    models.CharField(
                        auto_created=True,
                        default=backend.collab.models.editing_room.generate_room_id,
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collab.TextDocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CollabDocument",
            fields=[
                (
                    "textdocument_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="collab.TextDocument",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_pages",
                        to="collab.CollabDocument",
                    ),
                ),
            ],
            bases=("collab.textdocument",),
        ),
    ]
