# Generated by Django 3.0 on 2021-03-18 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recordmanagement", "0020_encryptedrecorddocumentdeletionrequest_record"),
        ("api", "0032_auto_20201125_0956"),
        ("collab", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollabPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(model_name="collabdocument", name="parent",),
        migrations.RemoveField(model_name="textdocument", name="content",),
        migrations.RemoveField(model_name="textdocument", name="name",),
        migrations.AddField(
            model_name="collabdocument",
            name="path",
            field=models.CharField(default="", max_length=4096),
        ),
        migrations.CreateModel(
            name="TextDocumentVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_draft", models.BooleanField(default=True)),
                ("content", models.BinaryField()),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="text_document_versions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="collab.TextDocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecordDocument",
            fields=[
                (
                    "textdocument_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="collab.TextDocument",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collab_documents",
                        to="recordmanagement.EncryptedRecord",
                    ),
                ),
            ],
            bases=("collab.textdocument",),
        ),
        migrations.CreateModel(
            name="PermissionForCollabDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collab_permissions",
                        to="collab.CollabDocument",
                    ),
                ),
                (
                    "group_has_permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_has_collab_permission",
                        to="api.Group",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_permission_for_document",
                        to="collab.CollabPermission",
                    ),
                ),
            ],
            options={
                "unique_together": {("permission", "group_has_permission", "document")},
            },
        ),
    ]
