# Generated by Django 3.0 on 2021-03-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collab", "0002_auto_20210318_1052"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collabdocument",
            name="path",
            field=models.CharField(max_length=4096),
        ),
    ]
