# Generated by Django 3.1.7 on 2021-03-30 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collab", "0003_auto_20210318_1059"),
    ]

    operations = [
        migrations.RemoveField(model_name="textdocument", name="last_edited",),
        migrations.RemoveField(model_name="textdocument", name="last_editor",),
    ]
