# Generated by Django 3.0 on 2021-01-07 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collab", "0003_textdocumentversion"),
    ]

    operations = [
        migrations.RemoveField(model_name="textdocument", name="content",),
    ]
