# Generated by Django 3.0 on 2021-03-15 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_auto_20201125_0956"),
        ("collab", "0004_remove_textdocument_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollabPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PermissionForCollabDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collab_permissions",
                        to="collab.CollabDocument",
                    ),
                ),
                (
                    "group_has_permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_has_collab_permission",
                        to="api.Group",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_permission_for_document",
                        to="collab.CollabPermission",
                    ),
                ),
            ],
            options={
                "unique_together": {("permission", "group_has_permission", "document")},
            },
        ),
    ]
