# Generated by Django 3.0 on 2021-03-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collab", "0005_collabpermission_permissionforcollabdocument"),
    ]

    operations = [
        migrations.RemoveField(model_name="collabdocument", name="parent",),
        migrations.AddField(
            model_name="collabdocument",
            name="path",
            field=models.CharField(default="/", max_length=4096),
        ),
    ]
