# Generated by Django 2.2 on 2019-04-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0003_auto_20190411_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='state',
            field=models.CharField(choices=[('op', 'open'), ('cl', 'closed'), ('wa', 'waiting'), ('wo', 'working')], max_length=2),
        ),
    ]
