# Generated by Django 2.2.2 on 2019-11-28 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recordmanagement", "0005_client_from_rlc"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordDeletionRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("explanation", models.CharField(max_length=4096)),
                ("requested", models.DateTimeField(auto_now_add=True)),
                ("processed_on", models.DateTimeField(null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("re", "requested"),
                            ("gr", "granted"),
                            ("de", "declined"),
                        ],
                        default="re",
                        max_length=2,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deletions_requested",
                        to="recordmanagement.Record",
                    ),
                ),
                (
                    "request_from",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request_processed",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="record_deletion_request_processed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
