# Generated by Django 2.2.8 on 2020-01-06 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_auto_20200104_1333'),
        ('recordmanagement', '0009_recordencryption'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now_add=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('name', models.BinaryField()),
                ('note', models.BinaryField()),
                ('phone_number', models.BinaryField()),
                ('from_rlc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e_client_from_rlc', to='api.Rlc')),
                ('origin_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e_clients', to='recordmanagement.OriginCountry')),
            ],
        ),
        migrations.CreateModel(
            name='EncryptedRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now_add=True)),
                ('first_contact_date', models.DateField(default=None, null=True)),
                ('last_contact_date', models.DateTimeField(default=None, null=True)),
                ('first_consultation', models.DateTimeField(default=None, null=True)),
                ('record_token', models.CharField(max_length=50, unique=True)),
                ('official_note', models.TextField(blank=True, null=True)),
                ('state', models.CharField(choices=[('op', 'open'), ('cl', 'closed'), ('wa', 'waiting'), ('wo', 'working')], max_length=2)),
                ('note', models.BinaryField()),
                ('consultant_team', models.BinaryField()),
                ('lawyer', models.BinaryField()),
                ('related_persons', models.BinaryField()),
                ('contact', models.BinaryField()),
                ('bamf_token', models.BinaryField()),
                ('foreign_token', models.BinaryField()),
                ('first_correspondence', models.BinaryField()),
                ('circumstances', models.BinaryField()),
                ('next_steps', models.BinaryField()),
                ('status_described', models.BinaryField()),
                ('additional_facts', models.BinaryField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e_records', to='recordmanagement.EncryptedClient')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e_records_created', to=settings.AUTH_USER_MODEL)),
                ('from_rlc', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e_record_from_rlc', to='api.Rlc')),
                ('tagged', models.ManyToManyField(blank=True, related_name='e_tagged', to='recordmanagement.RecordTag')),
                ('working_on_record', models.ManyToManyField(blank=True, related_name='working_on_e_record', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='recordencryption',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encryptions', to='recordmanagement.EncryptedRecord'),
        ),
        migrations.CreateModel(
            name='EncryptedRecordPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested', models.DateTimeField(auto_now_add=True)),
                ('processed_on', models.DateTimeField(null=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('re', 'requested'), ('gr', 'granted'), ('de', 'declined')], default='re', max_length=2)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_permissions_requested', to='recordmanagement.EncryptedRecord')),
                ('request_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_record_permissions_requested', to=settings.AUTH_USER_MODEL)),
                ('request_processed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e_record_permissions_processed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EncryptedRecordMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('message', models.BinaryField()),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_record_messages', to='recordmanagement.EncryptedRecord')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e_record_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EncryptedRecordDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.BigIntegerField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e_record_documents_created', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_record_documents', to='recordmanagement.EncryptedRecord')),
                ('tagged', models.ManyToManyField(blank=True, related_name='e_tagged', to='recordmanagement.RecordDocumentTag')),
            ],
        ),
        migrations.CreateModel(
            name='ClientEncryption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_key', models.BinaryField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encryptions', to='recordmanagement.EncryptedClient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_encryptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
