# Generated by Django 2.2.8 on 2020-08-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0016_missingrecordkey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryptedrecorddeletionrequest",
            name="explanation",
            field=models.CharField(default="", max_length=4096),
        ),
    ]
