# Generated by Django 3.0 on 2021-03-16 14:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recordmanagement', '0020_encryptedrecorddocumentdeletionrequest_record'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recordencryption',
            unique_together={('user', 'record')},
        ),
    ]
