# Generated by Django 3.0 on 2021-02-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0020_encryptedrecorddocumentdeletionrequest_record"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryptedrecord",
            name="record_token",
            field=models.CharField(max_length=50),
        ),
    ]
