# Generated by Django 3.0 on 2021-03-16 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_delete_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recordmanagement', '0021_auto_20210316_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedrecord',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encrypted_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='encryptedrecord',
            name='from_rlc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encrypted_records', to='api.Rlc'),
        ),
    ]
