# Generated by Django 3.0 on 2021-03-16 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0022_auto_20210316_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedrecordmessage',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='recordmanagement.EncryptedRecord'),
        ),
    ]
