# Generated by Django 3.1.7 on 2021-03-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordmanagement', '0023_auto_20210324_2136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MissingRecordKey',
        ),
    ]
