# Generated by Django 3.0 on 2021-03-18 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0024_auto_20210318_1152"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryptedrecordmessage",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="recordmanagement.EncryptedRecord",
            ),
        ),
    ]
