# Generated by Django 3.1.7 on 2021-03-30 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0021_auto_20210201_1130"),
        ("recordmanagement", "0025_remove_encryptedrecordpermission_can_edit"),
    ]

    operations = []
