# Generated by Django 3.1.7 on 2021-03-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0026_merge_20210330_1504"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryptedclient",
            name="note",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="encryptedclient",
            name="phone_number",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
