# Generated by Django 3.1.7 on 2021-03-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0027_auto_20210331_1055"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryptedclient",
            name="note",
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name="encryptedclient",
            name="phone_number",
            field=models.BinaryField(null=True),
        ),
    ]
