# Generated by Django 3.1.6 on 2021-05-13 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaluser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internal_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
