# Generated by Django 3.1.7 on 2021-03-24 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_auto_20200325_1331"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={"verbose_name": "File", "verbose_name_plural": "Files"},
        ),
        migrations.AlterModelOptions(
            name="folder",
            options={"verbose_name": "Folder", "verbose_name_plural": "Folders"},
        ),
        migrations.AlterModelOptions(
            name="permissionforfolder",
            options={
                "verbose_name": "PermissionForFolder",
                "verbose_name_plural": "PermissionsForFolders",
            },
        ),
    ]
