# Generated by Django 3.1.6 on 2021-06-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_file_exists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='last_editor',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='number_of_files',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='size',
        ),
    ]
