# Generated by Django 3.1.6 on 2021-06-02 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_auto_20210513_1441"),
        ("files", "0010_auto_20210602_1421"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissionforfolder",
            name="group_has_permission",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_has_folder_permissions",
                to="core.group",
            ),
        ),
    ]
