# Generated by Django 3.1.6 on 2021-06-09 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0014_auto_20210609_1133"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folder",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_folders",
                to="files.folder",
            ),
        ),
    ]
