# Generated by Django 3.2.10 on 2022-01-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0020_auto_20210727_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/file/'),
        ),
    ]
