# records
PERMISSION_CAN_ADD_RECORD_RLC = "records__add_record"
PERMISSION_VIEW_RECORDS_FULL_DETAIL_RLC = "records__access_all_records"
# files
PERMISSION_READ_ALL_FOLDERS_RLC = "files__read_all_folders"
PERMISSION_WRITE_ALL_FOLDERS_RLC = "files__write_all_folders"
PERMISSION_MANAGE_FOLDER_PERMISSIONS_RLC = "files__manage_permissions"
# collab
PERMISSION_READ_ALL_COLLAB_DOCUMENTS_RLC = "collab__read_all_documents"
PERMISSION_WRITE_ALL_COLLAB_DOCUMENTS_RLC = "collab__write_all_documents"
PERMISSION_MANAGE_COLLAB_DOCUMENT_PERMISSIONS_RLC = "collab__manage_permissions"
# admin
PERMISSION_MANAGE_GROUPS_RLC = "admin__manage_groups"
PERMISSION_MANAGE_USERS = "admin__manage_users"
PERMISSION_MANAGE_PERMISSIONS_RLC = "admin__manage_permissions"
PERMISSION_MANAGE_RECORD_TEMPLATES = "admin__manage_record_templates"
PERMISSION_MANAGE_RECORD_QUESTIONNAIRES = 'admin__manage_record_questionnaires'
PERMISSION_PROCESS_RECORD_DELETION_REQUESTS = "admin__manage_record_deletion_requests"
PERMISSION_PERMIT_RECORD_PERMISSION_REQUESTS_RLC = "admin__manage_record_access_requests"


def get_all_permissions_strings():
    return [
        # records
        PERMISSION_CAN_ADD_RECORD_RLC,
        PERMISSION_VIEW_RECORDS_FULL_DETAIL_RLC,
        # files
        PERMISSION_READ_ALL_FOLDERS_RLC,
        PERMISSION_WRITE_ALL_FOLDERS_RLC,
        PERMISSION_MANAGE_FOLDER_PERMISSIONS_RLC,
        # collab
        PERMISSION_MANAGE_COLLAB_DOCUMENT_PERMISSIONS_RLC,
        PERMISSION_READ_ALL_COLLAB_DOCUMENTS_RLC,
        PERMISSION_WRITE_ALL_COLLAB_DOCUMENTS_RLC,
        # admin
        PERMISSION_MANAGE_GROUPS_RLC,
        PERMISSION_MANAGE_USERS,
        PERMISSION_MANAGE_PERMISSIONS_RLC,
        PERMISSION_MANAGE_RECORD_TEMPLATES,
        PERMISSION_MANAGE_RECORD_QUESTIONNAIRES,
        PERMISSION_PROCESS_RECORD_DELETION_REQUESTS,
        PERMISSION_PERMIT_RECORD_PERMISSION_REQUESTS_RLC,
    ]


def get_all_collab_permissions():
    return [
        PERMISSION_MANAGE_COLLAB_DOCUMENT_PERMISSIONS_RLC,
        PERMISSION_WRITE_ALL_COLLAB_DOCUMENTS_RLC,
        PERMISSION_READ_ALL_COLLAB_DOCUMENTS_RLC,
    ]


def get_all_records_permissions():
    return [
        PERMISSION_VIEW_RECORDS_FULL_DETAIL_RLC,
        PERMISSION_CAN_ADD_RECORD_RLC,
    ]


def get_all_files_permissions():
    return [
        PERMISSION_READ_ALL_FOLDERS_RLC,
        PERMISSION_WRITE_ALL_FOLDERS_RLC,
        PERMISSION_MANAGE_FOLDER_PERMISSIONS_RLC,
    ]
