name: Acceptance Stage

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
      SCW_DOCKER_REGISTRY:
        required: true
      SCW_TOKEN:
        required: true

jobs:
  analyze:
    name: Analyze
    uses: ./.github/workflows/acceptance-stage--sonarcloud-analyze-code.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  test:
    name: Test The Docker Container
    uses: ./.github/workflows/acceptance-stage--test-docker-image.yml
    with:
      image: "${{ github.event.repository.name }}:${{ github.sha }}"
    secrets:
      SCW_DOCKER_REGISTRY: ${{ secrets.SCW_DOCKER_REGISTRY }}
      SCW_TOKEN: ${{ secrets.SCW_TOKEN }}
