name: Commit Stage

on:
  workflow_call:
    secrets:
      SCW_DOCKER_REGISTRY:
        required: true
      SCW_TOKEN:
        required: true
      SONAR_TOKEN:
        required: true

jobs:
  analyze:
    name: Analyze
    uses: ./.github/workflows/acceptance-stage--sonarcloud-analyze-code.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    name: Build Image
    uses: ./.github/workflows/commit-stage--build-image.yml
    with:
      image: ${{ github.event.repository.name }}
      version: ${{ github.sha }}
    secrets:
      SCW_DOCKER_REGISTRY: ${{ secrets.SCW_DOCKER_REGISTRY }}
      SCW_TOKEN: ${{ secrets.SCW_TOKEN }}

  test:
    name: Run Tests
    uses: ./.github/workflows/commit-stage--run-tests.yml

  precommit:
    name: Pre-Commit
    uses: ./.github/workflows/commit-stage--precommit-analyze.yml
